/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.action;

import java.io.PrintWriter;
import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
//import javax.sql.DataSource;
import com.mm.core.master.RootMaster;

/** 
 * MyEclipse Struts
 * Creation date: 06-30-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CityAction extends Action {
	RootMaster rootMaster= new RootMaster();
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		String codeStr = (request.getParameter("collcountry")!=null) ? (request.getParameter("collcountry").trim()) : "94~+91";
		String codeStrArr[]= codeStr.split("~");
		int numCId=Integer.parseInt(codeStrArr[0]);
		int numSId = (request.getParameter("collstate")!=null) ? Integer.parseInt(request.getParameter("collstate").trim()) : 0;
		int numPId = (request.getParameter("collplace")!=null) ? Integer.parseInt(request.getParameter("collplace").trim()) : 0;
		String strPlace = "";
		
		////System.out.println("numCId in City>....................."+numCId);
		////System.out.println("codeStr in City>....................."+numSId);
		
		//if(request.getParameter("collstate")!=null)
		//{
			
			Vector placeVec = rootMaster.getPlace(numCId, numSId, getDataSource(request, "main"));
			strPlace = getPlaceList(numPId, placeVec, numCId, numSId );
		//}
		//else
		//{
			//strPlace ="<select name=\"collegeCity\" class=\"input_multi_txt_box\" tabindex=\"8\">";
			//strPlace += "<option value=\"0\" Selected>Select</option>";
			//strPlace += "<option value=\"-1\">Others</option>";
			//strPlace += "</select>";
			
		//}
	    response.setContentType("text/html;charset=ISO-8859-1");
	    PrintWriter out = response.getWriter();
	    out.println(strPlace);
	    out.flush();
		return null;
	}
	
	private String getPlaceList(int numPId, Vector placeVec, int numCId, int numSId)
	{
		String strResult ="<select name=\"collegeCity\" tabindex=\"21\" onchange=\"retrieveCollegeURL('collegeList.do?collcountry="+numCId+"&collstate="+numSId+"&collcity='+this.value), showOth();\">";
		
		for(int i=0; i<placeVec.size(); i++)
		{
			Vector tempVec = (Vector)placeVec.elementAt(i);
			int numPlaceId = Integer.parseInt(tempVec.elementAt(0).toString().trim());
			String strPName = tempVec.elementAt(1).toString().trim();
			//////System.out.println("numPlaceId "+numPlaceId);
			//////System.out.println("strPName "+strPName);
			if(numPId == numPlaceId)
			{
				strResult += "<option value=\"" + numPlaceId + "\" Selected>" + strPName + "</option>";
			}
			else
			{
				strResult += "<option value=\"" + numPlaceId + "\">" + strPName + "</option>";
			}
		}
		strResult += "</select>";
		return strResult;
		
	}
}