
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.action;

import java.io.PrintWriter;
import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import javax.sql.DataSource;

import com.mm.core.master.RootMaster;

/** 
 * MyEclipse Struts
 * Creation date: 06-30-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CollegeListAction extends Action {
	RootMaster rootMaster= new RootMaster();
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		String StrCId = ((String)request.getParameter("collegeId")!=null) ? (String)request.getParameter("collegeId") : "0";
		
		int tabindex = (request.getParameter("tabindex")!=null) ? Integer.parseInt(request.getParameter("tabindex").trim()) : 22;
		String collegeid = (request.getParameter("college_id")!=null) ? request.getParameter("college_id").trim() : "0";		 
		int numTempCount = (request.getParameter("numCount") != null) ? Integer.parseInt(request.getParameter("numCount").trim()) : 0;
		
		String collcountry = (request.getParameter("collcountry")!=null) ? (request.getParameter("collcountry").trim()) : "94";	
		String codeStrArr[]= collcountry.split("~");
		int numCId=Integer.parseInt(codeStrArr[0]);
		
		String collstate = (request.getParameter("collstate")!=null) ? request.getParameter("collstate").trim() : "0";		 
		String collcity = (request.getParameter("collcity")!=null) ? request.getParameter("collcity").trim() : "0";	
		
		String othcollege = (request.getParameter("othcollege")!=null) ? request.getParameter("othcollege").trim() : "";
		
		//System.out.println("collcountry.....othcollege.....CollegeListAction .........."+collcountry);
		//System.out.println("collstate...........CollegeListAction.........."+collstate);
		//System.out.println("collcity...........CollegeListAction .........."+collcity);
		
		
		//int intCstate = Integer.parseInt(collstate);
		//int intCcity = Integer.parseInt(collcity);
		
		Vector collegeVec = rootMaster.getCollege(getDataSource(request, "main"),codeStrArr[0], collstate, collcity);
		Vector collegeVecCom = rootMaster.getCollegeCom(getDataSource(request, "main"),codeStrArr[0], collstate, collcity);
		
		Vector<Vector>resultVec = new Vector<Vector>();
		Vector<String>tempVec = new Vector<String>();
		
		tempVec.add("0");
		tempVec.add("Select");
		resultVec.add(tempVec);
		
		for(int i=0;i<collegeVecCom.size();i++)
		{	
			Vector teamp = (Vector)collegeVecCom.elementAt(i);
			Vector<String>teamp1 = new Vector<String>();
			
			String teampId = teamp.elementAt(0).toString();
			String collegefull_name = teamp.elementAt(1).toString()+ "-"+ teamp.elementAt(2).toString();
			System.out.println("collegefull_name.............."+collegefull_name);
			
			teamp1.add(teampId+"~1");
			teamp1.add(collegefull_name);
			
			resultVec.add(teamp1);
			
		}
		
		for(int i=0;i<collegeVec.size();i++)
		{
			Vector teamp = (Vector)collegeVec.elementAt(i);
			Vector<String>teamp1 = new Vector<String>();
			
			String teampId = teamp.elementAt(0).toString();
			
			teamp1.add(teampId+"~0");
			teamp1.add(teamp.elementAt(1).toString());
			
			resultVec.add(teamp1);
			
			
		}
		
		
		Vector<String>tempVec2 = new Vector<String>();
		tempVec2.add("-1");
		tempVec2.add("Other");
		resultVec.add(tempVec2);
		
		//System.out.println("resultVec...........CollegeListAction ....10......"+resultVec);
		
		String strCollege = getCollegList(StrCId, resultVec, tabindex, collegeid, numTempCount, codeStrArr[0], collstate, collcity );
		
	    response.setContentType("text/html;charset=ISO-8859-1");
	    PrintWriter out = response.getWriter();
	    out.println(strCollege);
	    out.flush();
		return null;
	}
	
	private String getCollegList(String StrCId, Vector collegeVec, int tabindex, String strCollegeid ,int numTempCount, String codeStrArr, String collstate, String collcity)
	{	
		numTempCount = numTempCount +1;
		String strResult = "";
				//////System.out.println("collegeid...........in .........."+strCollegeid);
				 strResult ="<select name=\"txtCollege_id\" tabindex=\"22\"  onchange=\"retrieveCollegeURL('collegeList.do?collcountry="+codeStrArr+"&collstate="+collstate+"&collcity="+collcity+"&college_id='+this.value)\" >";
				
				for(int i=0; i<collegeVec.size(); i++)
				{
					Vector tempVec = (Vector)collegeVec.elementAt(i);
					String CollegeId = tempVec.elementAt(0).toString().trim();			
						
					String strCName = tempVec.elementAt(1).toString().trim();
					
					if(strCollegeid.equalsIgnoreCase(CollegeId))
					{
						strResult += "<option value=\"" + CollegeId + "\" Selected>" + strCName + "</option>";
						
					}
					else
					{
						strResult += "<option value=\"" + CollegeId + "\">" + strCName + "</option>";
					}
				}
			
		
		
		strResult += "</select>";
		return strResult;
	}
	
	
}