/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.action;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashMap;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.mm.core.master.RootMaster;

/** 
 * MyEclipse Struts
 * Creation date: 06-30-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class FirstCreeationStateAction extends Action {
	RootMaster rootMaster= new RootMaster();
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		
		String codeStr = (request.getParameter("collcountry")!=null) ? request.getParameter("collcountry").trim() : "94~+91";
		int numSId = (request.getParameter("collstate")!=null) ? Integer.parseInt("0") : 0;
		HttpSession session = request.getSession();
		
		String codeStrArr[]= codeStr.split("~");
		int numCId=Integer.parseInt(codeStrArr[0]);
		int tabindex = 6;
		String strState = "";
		
		
		HashMap stateList = (HashMap)session.getAttribute("AllStates");
		
		if(request.getParameter("collcountry")!=null && numCId > 0)
		{
			strState = getStateList(numSId, numCId, stateList,tabindex);
		}
		else
		{
			strState ="<select name=\"companyState\"  tabindex=\"10\" onchange=\"retrieveCityFURL('firstCreeationCity.do?collcountry="+numCId+"&collstate='+this.value), showOth();\">";
			strState += "<option value=\"0\" Selected>Select</option>";
			strState += "<option value=\"-1\">Others</option>";
			strState += "</select>";
		}
		response.setContentType("text/html;charset=ISO-8859-1");
	    PrintWriter out = response.getWriter();
	    out.println(strState);
	    out.flush();
		return null;
	}
	
	
	
	private String getStateList(int numSid, int numCId, HashMap stateList,int tabindex)
	{
		String strResult = "";
		
		  
			ArrayList AllStates = (ArrayList)stateList.get(numCId);
		
			strResult ="<select name=\"companyState\" tabindex=\""+tabindex+"\" onchange=\"retrieveCityFURL('firstCreeationCity.do?collcountry="+numCId+"&collstate='+this.value), showOth();\">";
			  
			
			for(int i=0; i<AllStates.size(); i++)
			{
				ArrayList StatesArr = (ArrayList)AllStates.get(i);
				int numStateId = Integer.parseInt(StatesArr.get(0).toString().trim());
				String strSName = StatesArr.get(1).toString().trim();
			if(numSid == numStateId)
			{
				strResult += "<option value=\"" + numStateId + "\" Selected>" + strSName + "</option>";
			}
			else
			{
				strResult += "<option value=\"" + numStateId + "\">" + strSName + "</option>";
			}
		}
		strResult += "</select>";
			return strResult;
	}

}