/*
 * Generated by MyEclipse Struts
 * 
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.mm.struts.form.UserCreationForm;
import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;



/** 
 * MyEclipse Struts
 * Creation date: 06-08-2007
 * 
 * XDoclet definition:
 * @struts.action path="/commnitySelection" name="userCreationForm" input="/communityselection.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="login.jsp"
 * @struts.action-forward name="failure" path="communityselection.jsp"
 */
public class UserCreationAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String cat_name = "";
		Connection con = null;
		Statement stmt = null;
		ResultSet rs = null;
		DataSource dataSource = null;
		UserCreationForm userCreationForm = (UserCreationForm) form;// TODO Auto-generated method stub
		try
		{
			dataSource = getDataSource(request,"main");
			con = dataSource.getConnection();
			stmt = con.createStatement();
			rs = stmt.executeQuery("select * from category where cat_id=1");
			if(rs.next())
			{
				cat_name = rs.getString("cat_name");
				////System.out.println("cat_name>>>>>>>>>"+cat_name);
				if(cat_name.equalsIgnoreCase("Telecom"))
				{
					return mapping.findForward("success");
				}
			}
		}
		catch(SQLException e)
		{
			////System.out.println("in sql exception");
		}
		
		////System.out.println(userCreationForm.getLname());
		return mapping.findForward("failure");
	}
}