/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.advt.form;

import java.util.Vector;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;	
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.mm.struts.advt.form.ChangepassForm;
import com.mm.core.master.*;
import javax.sql.DataSource;
import java.util.*;

import org.apache.struts.validator.ValidatorForm;
/** 
 * MyEclipse Struts
 * Creation date: 20-06-2007
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class ChangepassForm extends ValidatorForm
{
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** text property */
	/** currpass property */
	/** pass property */
	/** password property */
	
	private String currpass = "";
	private String pass = "";
	private String password = "";
	private String userId = "";
	/*
	 * Generated Methods
	 */
	
	/** 
	 * Returns the currpass.
	 * @return String
	 */

	public String getCurrpass() {
		return currpass;
	}
	/** 
	 * Set the currpass.
	 * @param currpass The currpass to set
	 */
	public void setCurrpass(String currpass) {
		this.currpass = currpass;
	}
	/** 
	 * Returns the pass
	 * @return String
	 */

	public String getPass() {
		return pass;
	}
	/** 
	 * Set the pass.
	 * @param pass The pass to set
	 */
	public void setPass(String pass) {
		this.pass = pass;
	}
	/** 
	 * Returns the password.
	 * @return String
	 */

	public String getPassword() {
		return password;
	}
	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	/** 
	 * Returns the userId.
	 * @return String
	 */

	public String getUserId() {
		return this.userId;
	}

	/** 
	 * Set the conPassWord.
	 * @param conPassWord The conPassWord to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}
	
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest req)
	{
		ActionErrors errors = super.validate(mapping,req);
		
		if(!(this.pass.equals(this.password)))
		{
			errors.add("advtChangepassForm",new ActionError("errors.resource.match","password" , "retype password"));
		}
		
		return errors;
	}
	 

}	