/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.advt.action;

import java.io.IOException;


import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mm.core.master.AdvtMaster;
import com.mm.struts.advt.form.ComplaintForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-13-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class AdvtComplaintformAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException 
	{
		String target = new String("failuer");
		try
		{
			ComplaintForm cf = (ComplaintForm)form;
			AdvtMaster am = new AdvtMaster();
			
			HttpSession session = request.getSession();
//			Company Id
			String strCompId = (session.getAttribute("compId") !=null) ? session.getAttribute("compId").toString().trim(): "0";
//			Category Id
			//String strCatId = (String)session.getAttribute("catid");
			String strCatId = cf.getCmbcat();
			
			//////System.out.println("Company Id in Complaint Form Success "+strCompId);
			//////System.out.println("Category Id in Complaint Form Success "+strCatId);
			target = am.setComplaintUnnamedMap(cf, getDataSource(request, "advt"), Integer.parseInt(strCompId.trim()), Integer.parseInt(strCatId.trim()));
			session.setAttribute("catid", strCatId);
			//////System.out.println("Target in Complaint Form Success "+target);
			
		}
		catch ( Exception e ) 
		{
			e.printStackTrace();
			//System.err.println("Setting target to error");
			target = new String("error");
			ActionErrors errors = new ActionErrors();
			errors.add(ActionErrors.GLOBAL_ERROR, new ActionError("errors.database.error", e.getMessage()));
// 		 	Report any errors
		    if ( !errors.isEmpty() ) 
		    {
		    	saveErrors(request, errors);
		    }
		}
		return (mapping.findForward(target));
	}
}