/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.advt.action;

import java.io.PrintWriter;
import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mm.core.master.*;

/** 
 * MyEclipse Struts
 * Creation date: 07-03-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class BrandsExistingComplaintAction extends Action {
	/*
	 * Generated by MyEclipse Struts
	 * Template path: templates/java/JavaClass.vtl
	 */
	
		public ActionForward execute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response)throws Exception 
		{
			HttpSession session = request.getSession();
			String numCount = (String)session.getAttribute("numCount");
			int count = Integer.parseInt(numCount);
			int remander = count%2;
			
			AdvtMaster advtMaster = new AdvtMaster();
			RootMaster rootMaster = new RootMaster();
			
			String uId =(String)session.getAttribute("uId");
			String compId =(String)session.getAttribute("compId");
			
			////System.out.println("compId..in Action avdt ........."+compId);
			int regFlag= rootMaster.getRegisteredFlag(getDataSource(request, "advt"), compId);
			////System.out.println("regFlag..in Action avdt ........."+regFlag);
			
			Vector allRights =(Vector)session.getAttribute("allRights");
			String adminFlag = allRights.elementAt(18).toString();
			
			
			
			String pageid = (request.getParameter("pageid")!=null)? request.getParameter("pageid").trim() : "1";
			String aType = (request.getParameter("aType")!=null)? request.getParameter("aType").trim() : "0";
			String lowerSubTag = (request.getParameter("lowerSubTag")!=null)? request.getParameter("lowerSubTag").trim() : "1";
			
			//////System.out.println("lowerSubTag..in Action avdt ........."+lowerSubTag);
			
			String strShortBy = (request.getParameter("sby")!=null) ? request.getParameter("sby") : "creation_date";
			String strSOrder = "";
			String strComFIdOrder = "asc";
			String strCTitelOrder = "asc";
			String strDateOrder = "asc";
			
			if(request.getParameter("sby")!=null)
			{
				if(request.getParameter("fidorder")!=null)
				{
					if(request.getParameter("fidorder").trim().equalsIgnoreCase("asc"))
					{
						strSOrder = "desc";
						strComFIdOrder = "desc";
					}
					else if (request.getParameter("fidorder").trim().equalsIgnoreCase("desc"))
					{
						strSOrder = "asc";
						strComFIdOrder = "asc";
					}
				}
				
				if(request.getParameter("ctorder")!=null)
				{
					if(request.getParameter("ctorder").trim().equalsIgnoreCase("asc"))
					{
						strSOrder = "desc";
						strCTitelOrder = "desc";
					}
					else if (request.getParameter("ctorder").trim().equalsIgnoreCase("desc"))
					{
						strSOrder = "asc";
						strCTitelOrder = "asc";
					}
				}
				if(request.getParameter("dateorder")!=null)
				{
					if(request.getParameter("dateorder").trim().equalsIgnoreCase("asc"))
					{
						strSOrder = "desc";
						strDateOrder = "desc";
					}
					else if (request.getParameter("dateorder").trim().equalsIgnoreCase("desc"))
					{
						strSOrder = "asc";
						strDateOrder = "asc";
					}
				}
				
				
			}
			String strFShortBy = strShortBy+" "+strSOrder;
			int minVal = (request.getParameter("numMin")!=null) ? Integer.parseInt(request.getParameter("numMin")) : 0;
			int maxVal = 20;
			////System.out.println("countVec.............InboxAction......minVal..... "+minVal);
			////System.out.println("countVec.............InboxAction......maxVal..... "+maxVal);
		
			
			
			Vector<String> paramVec1 = new Vector<String>();
			paramVec1.add(uId);
			paramVec1.add(compId);
			paramVec1.add(adminFlag);
			paramVec1.add(pageid);
			
			
			Vector<String> paramVec = new Vector<String>();
			paramVec.add(String.valueOf(minVal));
			paramVec.add(String.valueOf(maxVal));		
			paramVec.add(strFShortBy);
			paramVec.add(uId);
			paramVec.add(compId);
			paramVec.add(adminFlag);
			paramVec.add(pageid);
			
			int Cid = Integer.parseInt(compId);
			int Uid = Integer.parseInt(uId);
			int aFid = Integer.parseInt(adminFlag);
			
			
			
			Vector comVec = new Vector();
			Vector comListVec = new Vector();
			String comList = "";
			
			if(pageid.equalsIgnoreCase("1")&& lowerSubTag.equalsIgnoreCase("1")){
				comVec = advtMaster.getUnderprocessList(getDataSource(request, "advt"),Cid,Uid,aFid);
				
					
					for(int i=0; i<comVec.size();i++)
						{
						comListVec = (Vector)comVec.elementAt(i);					
						int tempComId = Integer.parseInt(comListVec.elementAt(0).toString().trim());
						
						comList = comList + tempComId;
						if((i+1)<comVec.size()){
							comList = comList+",";  
							
						}
						
						}
					
					paramVec1.add(comList);
					paramVec.add(comList);
				}
				else{
					paramVec1.add(" ");
					paramVec.add(" ");
					}
				//////System.out.println("comList................on page."+comList);
			int totalRow = 0;
			Vector<Vector> userVec = new Vector<Vector>();
			
			paramVec1.add(lowerSubTag);
			paramVec.add(lowerSubTag);
			//////System.out.println("paramVec1 in Action..........."+paramVec1);
			//System.out.println("paramVec in Action..........."+paramVec);
					totalRow = advtMaster.getComplaintCount(getDataSource(request, "advt"), paramVec1);
					userVec= advtMaster.getBrandComplaintList(getDataSource(request, "advt"), paramVec);
			
				
				
				String strPageHtml = getPages(minVal, maxVal, totalRow,lowerSubTag,pageid,numCount);
			
			////System.out.println("totalRow..........."+totalRow);
			//System.out.println("result userVec......."+userVec);
			
			String strComplaintList = getComplaintList(strComFIdOrder, strCTitelOrder,strDateOrder, minVal, maxVal, totalRow, strPageHtml, userVec, pageid,lowerSubTag, regFlag, remander);
			//////System.out.println("Users "+strComplaintList);
			/**
		     * setContentType - text/html to write String on page.
		     * PrintWriter - This line use to get writer to write on page.
		     * out.println - use to write string. 
		     * 
		     */
			response.setContentType("text/html;charset=ISO-8859-1");
		    PrintWriter out = response.getWriter();
		    out.println(strComplaintList);
		    out.flush();
			
			// TODO Auto-generated method stub
			return null;
		}
		
		private String getComplaintList(String strComFIdOrder, String strCTitelOrder,String strDateOrder, int minVal, int maxVal, int totalRow, String strPageHtml, Vector userVec, String pageid,String lowerSubTag,int regFlag, int remander)
		{
			
			
			
			     
			String strValue = "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" >"; 
			
			if(userVec.size()==0)
			{if(lowerSubTag.equalsIgnoreCase("2"))
			{
				strValue += "<tr align=\"center\">";
				strValue += "<td height=\"400\" valign=\"center\" colspan=\"5\" class=\"bold\">Currently, there is no Query in your Outbox</td>";
				strValue += "</tr>";
			}else
			{
				strValue += "<tr align=\"center\">";
				strValue += "<td height=\"400\" valign=\"center\" colspan=\"5\" class=\"bold\">Currently, there is no Query in your Inbox</td>";
				strValue += "</tr>";
			}
			}
			else
			{
				
				if (totalRow > maxVal)
				{
		        strValue += "<tr >";
				strValue += "<td colspan=\"7\" align=\"right\" >Page Number  "+strPageHtml+"</td>";		
				strValue += "</tr>";
				}
				
			strValue += "<tr>";
	        strValue += "<td width=\"100%\">";
	           
		    strValue += "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" >"; 
		    
		    
		    strValue += "<tr>";	
		    strValue += "<td height=\"5\" colspan=\"7\" align=\"right\"><hr color=\"#C1C1C1\"></td>";	
		    strValue += "</tr>";
		    
		    
		    String strLoginIdSymbol = (strComFIdOrder.trim().equalsIgnoreCase("asc")) ? "<img style=\"cursor:hand\" src=\"../images/downarrow.gif\" onClick=\"retrieveClistURL('brandsExistingComplaint.do?sby=log.first_name&lowerSubTag="+lowerSubTag+"&pageid="+pageid+"&numMin="+ minVal+"&fidorder="+strComFIdOrder+"');\">" : "<img style=\"cursor:hand\" src=\"../images/uparrow.gif\" onClick=\"retrieveClistURL('brandsExistingComplaint.do?sby=log.first_name&lowerSubTag="+lowerSubTag+"&pageid="+pageid+"&numMin="+ minVal+"&fidorder="+strComFIdOrder+"');\">";
		    String strUnameSymbol = (strCTitelOrder.trim().equalsIgnoreCase("asc")) ? "<img style=\"cursor:hand\" src=\"../images/downarrow.gif\" onClick=\"retrieveClistURL('brandsExistingComplaint.do?sby=com.complaint_title&lowerSubTag="+lowerSubTag+"&pageid="+pageid+"&numMin="+ minVal+"&ctorder="+strCTitelOrder+"');\">" : "<img style=\"cursor:hand\" src=\"../images/uparrow.gif\" onClick=\"retrieveClistURL('brandsExistingComplaint.do?sby=com.complaint_title&lowerSubTag="+lowerSubTag+"&pageid="+pageid+"&numMin="+ minVal+"&ctorder="+strCTitelOrder+"');\">";
		    String strDateSymbol = (strDateOrder.trim().equalsIgnoreCase("asc")) ? "<img style=\"cursor:hand\" src=\"../images/downarrow.gif\" onClick=\"retrieveClistURL('brandsExistingComplaint.do?sby=com.creation_date&lowerSubTag="+lowerSubTag+"&pageid="+pageid+"&numMin="+ minVal+"&dateorder="+strDateOrder+"');\">" : "<img style=\"cursor:hand\" src=\"../images/uparrow.gif\" onClick=\"retrieveClistURL('brandsExistingComplaint.do?sby=com.creation_date&lowerSubTag="+lowerSubTag+"&pageid="+pageid+"&numMin="+ minVal+"&dateorder="+strDateOrder+"');\">";
			
		    strValue += "<tr height=\"20\" >";	
		    strValue += "<th class=\"bold\">&nbsp;S. No.</th>";
		    if(lowerSubTag.equalsIgnoreCase("1"))
			{
		    	 strValue += "<th class=\"bold\">Query from&nbsp;"+strLoginIdSymbol+"</th>";	
			}else
			{
				 strValue += "<th class=\"bold\">Reply sent to&nbsp;"+strLoginIdSymbol+"</th>";	
			}
		    
		       
		    strValue += "<th class=\"bold\">Title&nbsp;"+strUnameSymbol+"</th>";	
		    strValue += "<th class=\"bold\">Date&nbsp;"+strDateSymbol+"</th>";
		    strValue += "<th class=\"bold\">&nbsp;</th>";
		    
		    strValue += "</tr>";	
		    strValue += "<tr>";	
		    strValue += "<td height=\"5\" colspan=\"5\" align=\"right\"><hr color=\"#C1C1C1\"></td>";	
		    strValue += "</tr>";	
		
		   
		    
		    for(int i=0; i<userVec.size(); i++)
			{
		    	int j = i+1;
		    	int numTotal = j%2;
		    	String strColor = (numTotal==0) ? "#FFFFFF" : "#EDF3F8";
		    	String strImg = (numTotal==0) ? "detail_gray.gif" : "detail_white.gif";
			 Vector tempVec = (Vector)userVec.elementAt(i);
			 
			 int comId = Integer.parseInt(tempVec.elementAt(0).toString().trim());
			 
			 String strFid = tempVec.elementAt(1).toString().trim();
			 
			 String strFname = tempVec.elementAt(6).toString().trim();
			 String strLname = tempVec.elementAt(7).toString().trim();
			 String strCity = tempVec.elementAt(8).toString().trim();
			 
			 
//			 	for check length of Complaint text
			 String strText = "";  
			 String strFMsg = "";
			 
				String strMessage =  tempVec.elementAt(2).toString().trim();
				////////System.out.println("complaintMessage........."+strMessage.length());
				////////System.out.println("complaintMessage........."+strMessage);
				int numChar = (strMessage.length() > 45) ? 45 : strMessage.length();  
				for(int k=0; k<numChar; k++)
				{ 
					
						   strFMsg = strFMsg+strMessage.charAt(k);
						   
						
				}
				if(strFMsg.lastIndexOf(strFMsg)!=-1)
				{
					 strText= strFMsg;
					//////System.out.println("...strFMsgTeam......"+strFMsg.lastIndexOf(strFMsg));
					
		         
		        }else{
		        	strText= strFMsg.substring(0, strFMsg.lastIndexOf(" "));
		        	//////System.out.println("...strText......");
		        }
		     
		       String strDate[]=tempVec.elementAt(3).toString().trim().split("-");
			  
		    strValue += "<tr height=\"25\" align=\"center\" bgcolor=\""+strColor+"\">";
		    strValue += "<td height=\"20\" >&nbsp;"+j+"</td>";	
		    strValue += "<td align=\"center\" > "+strFname+" "+strLname+","+strCity+"</td>";	
		    strValue += "<td align=\"center\" > "+strText+"..</td>";	
		    strValue += "<td align=\"center\" > "+strDate[2]+"-"+strDate[1]+"-"+strDate[0]+"</td>";
		    if(regFlag!=0){
		    strValue += "<td ><a href=\"complaintDetail.jsp?pageid="+pageid+"&lowerSubTag="+lowerSubTag+"&numCompId="+comId+"&strPgType=Detail\"><img alt=\"Click here to see detail\" src=\"../images/"+strImg.trim()+"\" width=\"47\" height=\"19\" border=\"0\"></img></a></td>";	
		    }else{
		    	strValue += "<td ><img alt=\"Click here to see detail\" src=\"../images/"+strImg.trim()+"\" width=\"47\" height=\"19\" border=\"0\" onclick=\"showalert()\";></img></td>";	
		 	  }
		    strValue += "</tr>";	
		   	   
		    strValue += "</td>";	
		    strValue += "</tr>";
			}
		    
		    strValue += "<tr>";	
		    strValue += "<td height=\"20\" colspan=\"5\" align=\"right\"><hr color=\"#C1C1C1\"></td>";	
		    strValue += "</tr>";
		   
		    
		    if (totalRow > maxVal)
			{
	        strValue += "<tr >";
			strValue += "<td colspan=\"7\" align=\"right\" >Page Number"+strPageHtml+"</td>";		
			strValue += "</tr>";
			}
			
			}
			if(remander==0)
			{
				strValue += "<tr style=\"display:none\" align=\"center\">";
				strValue += "<td height=\"50\" colspan=\"5\"></td>";
				strValue += "</tr>";
			}
		    strValue += "</table>";	
		    
			return strValue;
		}
		
		private String getPages(int minVal, int maxVal, int numSize ,String lowerSubTag,String pageid ,String numCount)
		{
			String strResult ="<select name=\"paging\" onchange=\"retrieveClistURL('brandsExistingComplaint.do?lowerSubTag="+lowerSubTag+"&pageid="+pageid+"&numCount="+numCount+"&'+this.value);\">";
			int numMin = 0;
			int numPage = 1;
			for(int i=0; i<numSize; i=i+maxVal)
			{
				numMin = i;
				
				if(minVal == numMin)
				{
					strResult += "<option value=\"numMin=" + numMin+"\" Selected>Page" + numPage + "</option>";
				}
				else
				{
					strResult += "<option value=\"numMin=" + numMin+"\">Page" + numPage + "</option>";
				}
					numPage++;
			}
			strResult += "</select>";
			return strResult;
		}
	
	
}