/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.advt.action;

import java.io.PrintWriter;
import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mm.core.master.*;

/** 
 * MyEclipse Struts
 * Creation date: 07-16-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CorpoNameAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception 
	{
		HttpSession session = request.getSession();
		int numAdvtCId = (request.getParameter("category")!=null) ? Integer.parseInt(request.getParameter("category").trim()) : 0;
		int numAdvtId = (request.getParameter("advtid")!=null) ? Integer.parseInt(request.getParameter("advtid").trim()) : 0;
		String Qtype = (request.getParameter("Qtype")!=null) ? request.getParameter("Qtype").trim() : (String)session.getAttribute("Qtype");
		int numTempCount = (request.getParameter("numCount") != null) ? Integer.parseInt(request.getParameter("numCount").trim()) : 0;
		////////System.out.println("Company Id in Advt Category "+numAdvtId);
    	//.out.println("Catid Id in Advt Category "+numAdvtCId);
		String Arry[]={"0"};
		IndvMaster am = new IndvMaster();
		RootMaster rootMaster = new RootMaster();
		String compName = "";
		  Vector categoryVec=new Vector();
		if(Qtype.equalsIgnoreCase("Advertiser"))
		{
			 categoryVec =am.getNewCollege(numAdvtCId, getDataSource(request, "advt"),Arry[0]);
			 
			 compName="College";
			 
		}else
		{
			 categoryVec = am.getNewBrand(numAdvtCId, getDataSource(request, "advt"),Arry[0]);
			 
			 compName="Company";
		}
		Qtype="";
		String Mtype="0";
		/*Vector brandVec=new Vector();
		if(Qtype.equalsIgnoreCase("Advertiser"))
		{
		 brandVec = am.getNewCollege(numAdvtCId, getDataSource(request, "corpo"),Arry[0]);
		}else
		{
			brandVec = am.getNewBrand(numAdvtCId, getDataSource(request, "corpo"),Arry[0]);
		}*/
		 
		
		
		////////System.out.println("Result Vector in Advt Category "+resultVec);
		String strBrandCategory =getBrandCat(numTempCount, numAdvtCId, categoryVec,compName,numAdvtId,Qtype,Mtype);
		////////System.out.println("String Brand Category in Advt Category "+strBrandCategory);
	    response.setContentType("text/html;charset=ISO-8859-1");
	    PrintWriter out = response.getWriter();
	    out.println(strBrandCategory);
	    out.flush();
		return null;
	}
	
	private String getBrandCat(int numTempCount, int numAdvtCat, Vector CategoryVec,String compName,int numAdvtId,String Qtype,String Mtype)
	{
		String strResult ="<table width=\"100%\"><tr><td width=\"25%\" align=\"right\"><span class=\"bold\" >"+compName+" Name</span></td><td  width=\"75%\"><select name=\"brand\" id=\"brand\" onchange=\"retrieveContact_PresonURL('contactPerson.do?mcat="+Mtype+"&Qtype="+Qtype+"&cuid='+this.value),show()\" >";
		for(int i=0; i<CategoryVec.size(); i++)
		{
			Vector tempVec1 = (Vector)CategoryVec.elementAt(i);
			int numCatId = Integer.parseInt(tempVec1.elementAt(0).toString().trim());
			String strCatName = tempVec1.elementAt(1).toString().trim();
			////////System.out.println("numCountryId "+numCountryId);
			////////System.out.println("strCName "+strCName);
			if(numCatId == numAdvtCat)
			{
				strResult += "<option value=\"" + numCatId + "\" Selected>" + strCatName + "</option>";
			}
			else
			{
				strResult += "<option value=\"" + numCatId + "\">" + strCatName + "</option>";
			}
		}
		strResult += "</select></td></tr></table>";
		int numtotal = numTempCount/2;
		if(numtotal !=0)
		{
			strResult += "";
		}
		return strResult;
	}
}