/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.advt.action;

import java.io.PrintWriter;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import java.util.Vector;
import com.mm.core.master.*;

/** 
 * MyEclipse Struts
 * Creation date: 06-30-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CourseForColAction extends Action {
	RootMaster rootMaster= new RootMaster();
	IndvMaster indvMaster=new IndvMaster();
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
		// TODO Auto-generated method stub
		String StrCourseId = (request.getParameter("college_id")!=null) ? (request.getParameter("college_id").trim()) : "0";
		
		System.out.println("StrCourseId............ "+StrCourseId);
		
		String ary[]=StrCourseId.split("~");
		int tabindex = 0;
		
		int numCourseId=Integer.parseInt(ary[0]);
		
		String id=indvMaster.getCatForcomp(getDataSource(request,"advt"),numCourseId);
		if(id.equalsIgnoreCase("failure"))
		{
			id="0";
		}else
		{
			id=id+"0";
		}
		
		Vector CourseVec = indvMaster.getcatList(getDataSource(request,"advt"),id.trim());
		String strCourse ="";
		
	    strCourse = getCourseList(numCourseId, CourseVec,numCourseId);
		
	    response.setContentType("text/html;charset=ISO-8859-1");
	    PrintWriter out = response.getWriter();
	    out.println(strCourse);
	    out.flush();
		return null;
	}
	
	private String getCourseList(int numCid, Vector CountryVec,int numCourseId)
	{
		String strResult ="<table width=\"100%\"><tr><td width=\"25%\" align=\"right\"><span class=\"bold\" >Department</span></td><td  width=\"75%\"><select name=\"category\" onchange=\"retrieveStudentURL('stdList.do?college_id="+numCourseId+"&stream_id='+this.value)\"  >";
		
		for(int i=0; i<CountryVec.size()-1; i++)
		{
			Vector tempVec = (Vector)CountryVec.elementAt(i);
			
			int numCIdTemp=Integer.parseInt(tempVec.elementAt(0).toString().trim());			
			String strCName = tempVec.elementAt(1).toString().trim();
			
			if(numCid == numCIdTemp)
			{
				strResult += "<option value=\"" + numCIdTemp + "\" Selected>" + strCName + "</option>";
			}
			else
			{
				strResult += "<option value=\"" + numCIdTemp + "\">" + strCName + "</option>";
			}
		}
		strResult += "</select></td></tr>";
		if(CountryVec.size()==2)
		{
			strResult +="<tr><td width=\"25%\" align=\"right\"><span class=\"bold\" ></span></td><td  width=\"75%\"  align=\"left\">";
			strResult+="<span class=\"bold\" > &nbsp;&nbsp;No Student register under this College.<br>&nbsp;&nbsp;plz Select another College to write Your Reviews.</span></td></tr></table>";
		
		}
		return strResult;
	}
	
}