
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.advt.action;

import java.io.PrintWriter;
import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mm.core.master.*;

/** 
 * MyEclipse Struts
 * Creation date: 07-03-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ExistingTestListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)throws Exception 
	{
		HttpSession session = request.getSession();
		int numTempCount = (session.getAttribute("numCount") != null) ? Integer.parseInt((String)session.getAttribute("numCount")) : 0;
		numTempCount = numTempCount+1;
		RootMaster rootMaster = new RootMaster();
		session.setAttribute("numCount", String.valueOf(numTempCount));
		int remander = numTempCount%2;
		String compId =(String)session.getAttribute("compId");
		Vector allRights =(Vector)session.getAttribute("allRights");
		String adminFlag = allRights.elementAt(18).toString();
		int regFlag= rootMaster.getRegisteredFlag(getDataSource(request, "advt"), compId);
		String ptype = (request.getParameter("ptype")!=null)? request.getParameter("ptype").trim() : "Digital";
		////System.out.println("+ptype+ptype>>>>>>>>on Action>"+request.getParameter("ptype"));
		////System.out.println("+ptype+ptype>>>>>>>>on Action>"+ptype);
		String pageid = (request.getParameter("pageid")!=null)? request.getParameter("pageid").trim() : "3";
		String strShortBy = (request.getParameter("sby")!=null) ? request.getParameter("sby") : "testname";
		String strSOrder = "";
		String strComFIdOrder = "asc";
		String strCTitelOrder = "asc";
		String strDateOrder = "asc";
		
		if(request.getParameter("sby")!=null)
		{
			if(request.getParameter("fidorder")!=null)
			{
				if(request.getParameter("fidorder").trim().equalsIgnoreCase("asc"))
				{
					strSOrder = "desc";
					strComFIdOrder = "desc";
				}
				else if (request.getParameter("fidorder").trim().equalsIgnoreCase("desc"))
				{
					strSOrder = "asc";
					strComFIdOrder = "asc";
				}
			}
			
			if(request.getParameter("ctorder")!=null)
			{
				if(request.getParameter("ctorder").trim().equalsIgnoreCase("asc"))
				{
					strSOrder = "desc";
					strCTitelOrder = "desc";
				}
				else if (request.getParameter("ctorder").trim().equalsIgnoreCase("desc"))
				{
					strSOrder = "asc";
					strCTitelOrder = "asc";
				}
			}
			if(request.getParameter("dateorder")!=null)
			{
				if(request.getParameter("dateorder").trim().equalsIgnoreCase("asc"))
				{
					strSOrder = "desc";
					strDateOrder = "desc";
				}
				else if (request.getParameter("dateorder").trim().equalsIgnoreCase("desc"))
				{
					strSOrder = "asc";
					strDateOrder = "asc";
				}
			}
			
			
		}
		String strFShortBy = strShortBy+" "+strSOrder;
		int minVal = (request.getParameter("numMin")!=null) ? Integer.parseInt(request.getParameter("numMin")) : 0;
		int maxVal = 20;
		
		AdvtMaster advtMaster = new AdvtMaster();
		Vector<String> paramVec = new Vector<String>();
		paramVec.add(String.valueOf(minVal));
		paramVec.add(String.valueOf(maxVal));		
		paramVec.add(strFShortBy);
		paramVec.add(compId);
		paramVec.add(ptype);
		paramVec.add(pageid);
		
		
		Vector<Vector> userVec = new Vector<Vector>();
		
			
				
				userVec= advtMaster.getExistingTestList(getDataSource(request, "advt"), paramVec);
		
			
			
			
		String strComplaintList = "";
		 strComplaintList = getComplaintList(strComFIdOrder, strCTitelOrder,strDateOrder, minVal,  userVec, pageid, remander, regFlag,numTempCount,ptype);
		
		/**
	     * setContentType - text/html to write String on page.
	     * PrintWriter - This line use to get writer to write on page.
	     * out.println - use to write string. 
	     * 
	     */
		response.setContentType("text/html;charset=ISO-8859-1");
	    PrintWriter out = response.getWriter();
	    out.println(strComplaintList);
	    out.flush();
		
		// TODO Auto-generated method stub
		return null;
	}
	
	private String getComplaintList(String strComFIdOrder, String strCTitelOrder,String strDateOrder, int minVal,  Vector userVec, String pageid, int remander,int regFlag,int numTempCount,String ptype)
	{
		
		
		     
		String strValue = "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" >"; 
		
		if(userVec.size()==0)
		{
			strValue += "<tr align=\"center\">";
			strValue += "<td height=\"375\" valign=\"center\" colspan=\"7\" class=\"bold\"> You have not created any test yet. </td>";
			strValue += "</tr>";
		}
		else
		{
		strValue += "<tr>";
        strValue += "<td width=\"100%\">";
        strValue += "<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" >"; 
	    strValue += "<tr>";	
	    strValue += "<td height=\"5\" colspan=\"7\" align=\"right\"><hr color=\"#C1C1C1\"></td>";	
	    strValue += "</tr>";
	    
	    String strLoginIdSymbol = (strComFIdOrder.trim().equalsIgnoreCase("asc")) ? "<img style=\"cursor:hand\" src=\"../images/downarrow.gif\" onClick=\"retrieveETestlistURL('existingTestList.do?numCount="+numTempCount+"&ptype="+ptype+"&sby=testname&numMin="+ minVal+"&fidorder="+strComFIdOrder+"');\">" : "<img style=\"cursor:hand\" src=\"../images/uparrow.gif\" onClick=\"retrieveETestlistURL('existingTestList.do?numCount="+numTempCount+"&ptype="+ptype+"&sby=testname&numMin="+ minVal+"&fidorder="+strComFIdOrder+"');\">";
	    String strUnameSymbol = (strCTitelOrder.trim().equalsIgnoreCase("asc")) ? "<img style=\"cursor:hand\" src=\"../images/downarrow.gif\" onClick=\"retrieveETestlistURL('existingTestList.do?numCount="+numTempCount+"&ptype="+ptype+"&sby=testtype&numMin="+ minVal+"&ctorder="+strCTitelOrder+"');\">" : "<img style=\"cursor:hand\" src=\"../images/uparrow.gif\" onClick=\"retrieveETestlistURL('existingTestList.do?numCount="+numTempCount+"&ptype="+ptype+"&sby=testtype&numMin="+ minVal+"&ctorder="+strCTitelOrder+"');\">";
	    String strDateSymbol = (strDateOrder.trim().equalsIgnoreCase("asc")) ? "<img style=\"cursor:hand\" src=\"../images/downarrow.gif\" onClick=\"retrieveETestlistURL('existingTestList.do?numCount="+numTempCount+"&ptype="+ptype+"&sby=testcategory&numMin="+ minVal+"&dateorder="+strDateOrder+"');\">" : "<img style=\"cursor:hand\" src=\"../images/uparrow.gif\" onClick=\"retrieveETestlistURL('existingTestList.do?numCount="+numTempCount+"&ptype="+ptype+"&sby=testcategory&numMin="+ minVal+"&dateorder="+strDateOrder+"');\">";
		
	    strValue += "<tr height=\"20\" >";	
	    strValue += "<th class=\"bold\">&nbsp;S. No.</th>";
	    strValue += "<th class=\"bold\">Test Name&nbsp;"+strLoginIdSymbol+"</th>";	    
	    strValue += "<th class=\"bold\">Test Type&nbsp;"+strUnameSymbol+"</th>";	
	    strValue += "<th class=\"bold\">Test Category&nbsp;"+strDateSymbol+"</th>";
	    strValue += "<th class=\"bold\">&nbsp;</th>";
	    
	    strValue += "</tr>";	
	    strValue += "<tr>";	
	    strValue += "<td height=\"5\" colspan=\"7\" align=\"right\"><hr color=\"#C1C1C1\"></td>";	
	    strValue += "</tr>";	
	
	   
	    
	    for(int i=0; i<userVec.size(); i++)
		{
	    	int j = i+1;
	    	int numTotal = j%2;
	    	String strColor = (numTotal==0) ? "#FFFFFF" : "#EDF3F8";
	    	String strImg = (numTotal==0) ? "detail_gray.gif" : "detail_white.gif";
	    	Vector tempVec = (Vector)userVec.elementAt(i);
	    	String Tstid=tempVec.elementAt(0).toString().trim();
	    	String ttype= tempVec.elementAt(2).toString().trim();
	    //for check length of Complaint text
			 String strText = "";  
			 String strFMsg = "";
			 
				String strMessage =  tempVec.elementAt(1).toString().trim();
				int numChar = (strMessage.length() > 45) ? 45 : strMessage.length();  
				for(int k=0; k<numChar; k++)
				{ 	   strFMsg = strFMsg+strMessage.charAt(k);
						
				}
				if(strFMsg.lastIndexOf(strFMsg)!=-1)
				{ strText= strFMsg;
				
		        }else{
		        	strText= strFMsg.substring(0, strFMsg.lastIndexOf(" "));
		        }
			
	    String strCat = tempVec.elementAt(3).toString().trim();
	    strValue += "<tr height=\"25\" align=\"center\" bgcolor=\""+strColor+"\">";
	    strValue += "<td height=\"20\" >&nbsp;"+j+"</td>";	
	    strValue += "<td align=\"center\" > "+strText+"..</td>";	
	    strValue += "<td align=\"center\" > "+ttype+"</td>";	
	    strValue += "<td align=\"center\" > "+strCat+"</td>";	
	    if(regFlag!=0){
		    strValue += "<td ><a href=\"testdata.do?reqtyp=Edit&testtyp="+ttype+"&tstid="+Tstid+"\" class=\"bold\">Modify</a></td>";
		    strValue += "<td >&nbsp;</td>";
		    //strValue += "<td ><a href=\"testdata.do?reqtyp=Detail&testtyp="+ttype+"&tstid="+Tstid+"\"><img alt=\"Click here to see detail\" src=\"../images/"+strImg.trim()+"\" width=\"47\" height=\"19\" border=\"0\"></img></a></td>";	
		    
		    
	    }else{
		    	strValue += "<td class=courser:hand  onclick=\"showalert()\" ><span class=\"bold\">Modify</span></td>";	
		    	strValue +="<td ><img alt=\"Click here to see detail\" src=\"../images/"+strImg.trim()+"\" width=\"47\" height=\"19\" border=\"0\" onclick=\"showalert()\";></img></td>";	
		    	
	    }
	    strValue += "</tr>";	
	   	strValue += "</td>";	
	    strValue += "</tr>";
		}
	    strValue += "<tr>";	
	    strValue += "<td height=\"20\" colspan=\"7\" align=\"right\"><hr color=\"#C1C1C1\"></td>";	
	    strValue += "</tr>";
	   }
		if(remander==0)
		{
			strValue += "<tr style=\"display:none\" align=\"center\">";
			strValue += "<td height=\"50\" colspan=\"7\"></td>";
			strValue += "</tr>";
		}
	    strValue += "</table>";	
	    
		return strValue;
	}
	
	
	
	
}