 
package com.mm.struts.corpo.action;

/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.mm.struts.corpo.form.ChangepassForm;
import java.util.Vector;
import com.mm.core.master.*;
import com.mm.core.resource.Constant;
import com.mm.core.resource.MailText;
import com.mm.core.resource.Resource;

import javax.sql.DataSource;


/** 
 * MyEclipse Struts
 * Creation date: 20-06-2007
 * 
 * XDoclet definition:
 * @struts.action path="/Changepass" name="ChangepassForm" input="/Changepass.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/Changepass.jsp"
 * @struts.action-forward name="failure" path="/Changepass.jsp"
 */

public class ChangepassAction extends Action{
	/*
	 * Generated Methods
	 */
	EntpMaster objectStr = new EntpMaster();

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,HttpServletRequest request, HttpServletResponse response) {
		ChangepassForm changepassForm = (ChangepassForm) form;// TODO Auto-generated method stub
		
		Vector <String> datavec = new Vector<String>();		
		
		DataSource ds = getDataSource(request,"corpo");
		RootMaster rootMaster = new RootMaster();
		String currentPassword = "";
		String result = "result";
		String userId = (request.getParameter("userId")!=null)? request.getParameter("userId").trim() : (String)request.getAttribute("userId"); 
		request.setAttribute("userId", userId);
		int intUserId = Integer.parseInt(userId);
		//////System.out.println("userId....on ....ChangepassAction....."+userId);
		
		currentPassword = rootMaster.getPassWord(ds,intUserId);
		
		//////System.out.println("currentPassword....on ....currentPassword....."+currentPassword);
		//////System.out.println("changepassForm.getCurrpass().toString()....on ....currentPassword....."+changepassForm.getCurrpass().toString());
		
		if(!currentPassword.equals(changepassForm.getCurrpass().toString()))
		{
			//////System.out.println("..in side if  .........");
			ActionErrors errors = new ActionErrors();
			errors.add("notExistPassword", new ActionError("errors.user.notExistPassword"));
			
				saveErrors(request, errors);
			
			return mapping.findForward("failure");
			
		}
		
		if(currentPassword.equalsIgnoreCase(changepassForm.getCurrpass().toString())){
		
		datavec.add(userId);//0				
		datavec.add(changepassForm.getPass());//1
		
		result = rootMaster.changPassWord(ds,datavec);
		
			if(result.equalsIgnoreCase("success")){
				ActionErrors errors = new ActionErrors();
	           	errors.clear();
	          	errors.add("changPassWord", new ActionError("errors.entp.changPassWordSuccess"));
				saveErrors(request, errors);
				result = "success";
			}
		
		}
		
		Vector<String> paramVec = new Vector<String>();
		IndvMaster indvMaster = new IndvMaster();
		
		if(!result.equalsIgnoreCase("failure"))
		{
			paramVec.add(userId);			
			Vector emailVec = indvMaster.getEmailList(ds, paramVec);
			Vector UserVec = (Vector)emailVec.elementAt(0);
			String userName =UserVec.elementAt(0).toString()+" "+UserVec.elementAt(1).toString();
			String usermail = UserVec.elementAt(2).toString().trim();
			String subject = "Your Password is changed";
			
			Vector userVec = rootMaster.getUserInfo(ds, Integer.parseInt(userId));
			String loginName = userVec.elementAt(2).toString();
			
			Resource resr = new Resource();
			MailText mt = new MailText();
			String strMailText = "";
			strMailText = mt.getChangedPassWord(userName, changepassForm.getPass(), loginName);
			result = resr.sendMail(strMailText, Constant.Email_Sender,usermail , subject);
			//////System.out.println("result>>>mail>>advt>>>"+result);
		}
		
		
		if(result.equalsIgnoreCase("success"))
		{
			return mapping.findForward("success");
		}
		else{
			
		return mapping.findForward("failure");
		}
	}
}

