/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.corpo.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.mm.struts.corpo.form.CorpoDataForm;
import com.mm.core.master.*;

import javax.sql.DataSource;

import java.text.SimpleDateFormat;
import java.util.StringTokenizer;
import java.util.Vector;




/** 
 * MyEclipse Struts
 * Creation date: 06-11-2007
 * 
 * XDoclet definition:
 * @struts.action path="/CorpoData" name="CorpoDataForm" input="/form/CorpoData.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="CorpoData.jsp"
 */
public class CorpoDataPreAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,HttpServletRequest request, HttpServletResponse response) {
		CorpoDataForm corpoDataForm = (CorpoDataForm) form;// TODO Auto-generated method stub
		
		
		Vector <String> dataVec = new Vector<String>();
		
		DataSource dataSource = getDataSource(request,"corpo");
		IndvMaster indvMaster = new IndvMaster();
		
		HttpSession session = request.getSession();
		String compId =(String)session.getAttribute("compId");
		dataVec.add(compId);
		
		
		
		
		
		Vector tabVec = indvMaster.getTabDetails(dataSource, dataVec);
		if(tabVec.size()>0)
		
		
		{
			corpoDataForm.setTab1(tabVec.elementAt(0).toString().trim());
			corpoDataForm.setTab2(tabVec.elementAt(1).toString().trim());
			corpoDataForm.setTab3(tabVec.elementAt(2).toString().trim());
			corpoDataForm.setTab4(tabVec.elementAt(3).toString().trim());
			corpoDataForm.setTab5(tabVec.elementAt(4).toString().trim());	
			
		}else
		{
			
	Vector paramVec=new Vector();
			
	String strValue4="";
	
	strValue4+="<TABLE align=\"center\">";
	strValue4+="<tr align=\"center\">";
	strValue4+="<td>&nbsp;";
	strValue4+="</td>";
	strValue4+="<td colspan=\"2\" align=\"center\"> ";
	strValue4+="<div align=\"center\" > <img  src=\"../images/noprofile.jpg\" width=\"100%\" height=\"100%\">";
	strValue4+="</div>";
	strValue4+="</td>";
	strValue4+="<td>&nbsp;";
	strValue4+="</td>";
	strValue4+="</tr>";
	strValue4+="</TABLE>";

	String strValue3="";
	
	strValue3+="<TABLE align=\"center\">";
	strValue3+="<tr align=\"center\">";
	strValue3+="<td>&nbsp;";
	strValue3+="</td>";
	strValue3+="<td colspan=\"2\" align=\"center\">";
	strValue3+="<div align=\"center\" > <img  src=\"../images/noprofile.jpg\" width=\"100%\" height=\"100%\">";
	strValue3+="</div>";
	strValue3+="</td>";
	strValue3+="<td>&nbsp;";
	strValue3+="</td>";
	strValue3+="</tr>";
	strValue3+="</TABLE>";

	String strValue2="";
	
	strValue2+="<TABLE align=\"center\">";
	strValue2+="<tr align=\"center\">";
	strValue2+="<td>&nbsp;";
	strValue2+="</td>";
	strValue2+="<td colspan=\"2\" align=\"center\">";
	strValue2+="<div align=\"center\" > <img  src=\"../images/noprofile.jpg\" width=\"100%\" height=\"100%\">";
	strValue2+="</div>";
	strValue2+="</td>";
	strValue2+="<td>&nbsp;";
	strValue2+="</td>";
	strValue2+="</tr>";
	strValue2+="</TABLE>";

	String strValue1="";
	
	strValue1+="<TABLE align=\"center\">";
	strValue1+="<tr align=\"center\">";
	strValue1+="<td>&nbsp;";
	strValue1+="</td>";
	strValue1+="<td colspan=\"2\" align=\"center\">";
	strValue1+="<div align=\"center\" > <img  src=\"../images/noprofile.jpg\" width=\"100%\" height=\"100%\">";
	strValue1+="</div>";
	strValue1+="</td>";
	strValue1+="<td>&nbsp;";
	strValue1+="</td>";
	strValue1+="</tr>";
	strValue1+="</TABLE>";
	
	String strValue5="";
	
	strValue5+="<TABLE align=\"center\">";
	strValue5+="<tr align=\"center\">";
	strValue5+="<td>&nbsp;";
	strValue5+="</td>";
	strValue5+="<td colspan=\"2\" align=\"center\">";
	strValue5+="<div align=\"center\" > <img  src=\"../images/noprofile.jpg\" width=\"100%\" height=\"100%\">";
	strValue5+="</div>";
	strValue5+="</td>";
	strValue5+="<td>&nbsp;";
	strValue5+="</td>";
	strValue5+="</tr>";
	strValue5+="</TABLE>";
			
			
			
			java.util.Date dt = new java.util.Date();
			SimpleDateFormat sform = new SimpleDateFormat("yyyy-MM-dd, HH:mm:ss,a");
			String completeRemDate = sform.format(dt);
			StringTokenizer sttotal = new StringTokenizer(completeRemDate, ",");
		    String creationDate = sttotal.nextToken();
		    String creationTime = sttotal.nextToken();
		    String timePart = sttotal.nextToken();
			 paramVec.add(compId);
			 paramVec.add("About Us");
			 paramVec.add("Product & Services");
			 paramVec.add("Recruitment");
			 paramVec.add("Work Culture");
			 paramVec.add("Announcements");
			 paramVec.add(strValue1);
			 paramVec.add(strValue2);
			 paramVec.add(strValue3);
			 paramVec.add(strValue4);
			 paramVec.add(strValue5);
			 paramVec.add(creationDate);
			 
			 AdvtMaster advtMaster=new AdvtMaster();
			 String strComplResult = advtMaster.insertTab(dataSource, paramVec);
			
			tabVec = indvMaster.getTabDetails(dataSource, dataVec);
			corpoDataForm.setTab1(tabVec.elementAt(0).toString().trim());
			corpoDataForm.setTab2(tabVec.elementAt(1).toString().trim());
			corpoDataForm.setTab3(tabVec.elementAt(2).toString().trim());
			corpoDataForm.setTab4(tabVec.elementAt(3).toString().trim());
			corpoDataForm.setTab5(tabVec.elementAt(4).toString().trim());	
		}
			
		corpoDataForm.setTabText1(tabVec.elementAt(5).toString().trim());
		corpoDataForm.setTabText2(tabVec.elementAt(6).toString().trim());
		corpoDataForm.setTabText3(tabVec.elementAt(7).toString().trim());
		corpoDataForm.setTabText4(tabVec.elementAt(8).toString().trim());
		corpoDataForm.setTabText5(tabVec.elementAt(9).toString().trim());
		
		request.setAttribute("corpoDataForm", corpoDataForm);
		
		
		if("request".equals(mapping.getScope()) ) 
		{
			request.setAttribute(mapping.getAttribute(), form);
	    }
	    else 
	    {
        	session.setAttribute(mapping.getAttribute(), form);
	    }
		request.setAttribute("tabVec", tabVec);
		//////System.out.println("result1result1>>>>>>>>>>>>in Pre action"+mapping.findForward("success"));
		
		return mapping.findForward("success");
		
	}

}

	
