/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.corpo.action;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mm.core.master.*;

/** 
 * MyEclipse Struts
 * Creation date: 07-03-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ExistingMembersAction extends Action {
	/*
	 * Generated Methods
	 * Ajay Kumar Jha
	 */

	/** 
	 * Method execute 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response)throws Exception 
	{
		HttpSession session =request.getSession();
	
		//String numCount = (String)session.getAttribute("numCount");
	
		//int count = Integer.parseInt(numCount);
		//int remander = count%2;
		
		String compId =(String)session.getAttribute("fId");
		AdvtMaster advtMaster = new AdvtMaster();
		
		ArrayList arrUsers = advtMaster.getResidentList(getDataSource(request,"corpo"), Integer.parseInt(compId));
		
		System.out.println("compId..in Action avdt ........."+compId);
		
		String strResult = getUserList(arrUsers);
		System.out.println("Users Result "+strResult);
		/**
	     * setContentType - text/html to write String on page.
	     * PrintWriter - This line use to get writer to write on page.
	     * out.println - use to write string. 
	     * 
	     */
		response.setContentType("text/html;charset=ISO-8859-1");
	    PrintWriter out = response.getWriter();
	    out.println(strResult);
	    out.flush();
		
		// TODO Auto-generated method stub
		return null;
	}
	
	private String getUserList(ArrayList arrUsers)
	{
		String strValue = "<div class=\"Fields_Row_2_head\">";
		strValue += "<div class=\"Row_2_Fields_check3\" style=\"margin-left:5px;\">&nbsp;</div>";
		strValue += "<div class=\"Row_2_Fields_head_2\" style=\"width:16%; margin-left:10px\">Resident Name</div>";
		strValue += "<div class=\"Row_2_Fields_head_2\" style=\"width:10%; margin-left:10px\">Type</div>";
		strValue += "<div class=\"Row_2_Fields_head_2\" style=\"width:12%; margin-left:10px;\">Occupancy Status</div>";
		strValue += "<div class=\"Row_2_Fields_head_2\" style=\"width:9%; margin-left:10px;\">Member Since</div>";
		strValue += "<div class=\"Row_2_Fields_head_2\" style=\"width:10%; margin-left:10px;\">Validated</div>";
		strValue += "<div class=\"Row_2_Fields_head_2\" style=\"width:12%; margin-left:10px;\">Suspended</div>";
		strValue += "<div class=\"Row_2_Fields_head_2\" style=\"width:9%; margin-left:10px;\">Registration Status</div>";
		strValue += "</div>";
		if(arrUsers.size()>0)
		{
			for(int i=0; i<arrUsers.size(); i++)
			{
				ArrayList arrData = (ArrayList)arrUsers.get(i);
				strValue += "<div class=\"Fields_Row_3a\">";
				strValue += "<div class=\"Row_2_Fields_check3\" style=\"margin-left:5px;\">";
				strValue += "<input name=\"chkUids\" type=\"checkbox\" onClick=\"setData()\" value=\""+arrData.get(0).toString().trim()+"\"/>";
				strValue += "</div>";
				strValue += "<div class=\"Row_3_Fields_Col_2\" style=\"width:16%; margin-left:10px\">";
				strValue += arrData.get(1).toString().trim()+" "+arrData.get(2).toString().trim();
				strValue += "</div>";
				strValue += "<div class=\"Row_3_Fields_Col_2\" style=\"width:10%; margin-left:10px\">";
				strValue += arrData.get(3).toString().trim();
				strValue += "</div>";
				strValue += "<div class=\"Row_3_Fields_Col_2\" style=\"width:12%; margin-left:10px\">";
				strValue += "Occupied";
				strValue += "</div>";
				strValue += "<div class=\"Row_3_Fields_Col_2\" style=\"width:11%; margin-left:10px\">";
				strValue += arrData.get(4).toString().trim();
				strValue += "</div>";
				strValue += "<div class=\"Row_3_Fields_Col_2\" style=\"width:10%; margin-left:10px\">";
				strValue += (Integer.parseInt(arrData.get(5).toString().trim())==1) ? "Yes" : "No";
				strValue += "</div>";
				strValue += "<div class=\"Row_3_Fields_Col_2\" style=\"width:10%; margin-left:10px\">";
				strValue += (Integer.parseInt(arrData.get(6).toString().trim())==1) ? "Yes" : "No";
				strValue += "</div>";
				strValue += "<div class=\"Row_3_Fields_Col_2\" style=\"width:8%; text-align:center; margin-left:10px\">";
				strValue += "Online";
				strValue += "</div>";
				strValue += "<div class=\"Row_3_Fields_Col_2\" style=\"width:1%; text-align:center; margin-left:10px\">";
				strValue += "<img id=\"showplus"+i+"\" style=\"cursor:pointer\" onclick=\"fnShow('User"+i+"', 'showplus"+i+"', 'showminus"+i+"')\" src=\"../images/checkboxhome.jpg\" width=\"15\" height=\"13\" /> <img id=\"showminus"+i+"\" style=\"display:none\" onclick=\"fnHide('User"+i+"', 'showplus"+i+"', 'showminus"+i+"')\" src=\"../images/close.gif\" width=\"17\" height=\"17\" />";
				strValue += "</div>";
				
				strValue += "<fieldset align=\"center\" id=\"User"+i+"\" style=\"display:none\"><div class=\"Fields_Row_3a\">";
				strValue += "<div class=\"Row_2_Fields_Col_2\" style=\"width:11%; margin-left:10px\">";
				strValue += "Address: - ";
				strValue += "</div>";
				strValue += "<div class=\"Row_2_Fields_Col_2\" style=\"width:10%; margin-left:10px\">";
				strValue += arrData.get(7).toString().trim();
				strValue += "</div>";
				strValue += "<div class=\"Row_2_Fields_Col_2\" style=\"width:11%; margin-left:10px\">";
				strValue += "Mobile No: - ";
				strValue += "</div>";
				strValue += "<div class=\"Row_2_Fields_Col_2\" style=\"width:10%; margin-left:10px\">";
				strValue += arrData.get(8).toString().trim();
				strValue += "</div>";
				strValue += "<div class=\"Row_2_Fields_Col_2\" style=\"width:11%; margin-left:10px\">";
				strValue += "Phone No: - ";
				strValue += "</div>";
				strValue += "<div class=\"Row_2_Fields_Col_2\" style=\"width:8%; text-align:center; margin-left:10px\">";
				strValue += arrData.get(9).toString().trim();
				strValue += "</div>";
				strValue += "</div></fieldset>";
			}
		}
		else
		{
			strValue += "<div class=\"Fields_Row_3a\">";
			strValue += "<div class=\"Row_3_Fields_Col_2\" style=\"width:100%; text-align:center; margin-left:10px\">";
			strValue += "No Record found.";
			strValue += "</div>";
		}
		strValue += "</div>";
		
		return strValue;
	}
	
	
	
	private String getPages(int minVal, int maxVal, int numSize ,String lowerSubTag,String pageid ,String numCount)
	{
		String strResult ="<select name=\"paging\" onchange=\"retrieveClistURL('brandsExistingComplaint.do?lowerSubTag="+lowerSubTag+"&pageid="+pageid+"&numCount="+numCount+"&'+this.value);\">";
		int numMin = 0;
		int numPage = 1;
		for(int i=0; i<numSize; i=i+maxVal)
		{
			numMin = i;
			
			if(minVal == numMin)
			{
				strResult += "<option value=\"numMin=" + numMin+"\" Selected>Page" + numPage + "</option>";
			}
			else
			{
				strResult += "<option value=\"numMin=" + numMin+"\">Page" + numPage + "</option>";
			}
				numPage++;
		}
		strResult += "</select>";
		return strResult;
	}
}