/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.corpo.action;

import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.commons.dbcp.DataSourceConnectionFactory;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mm.resource.APPConstant;
import com.mm.struts.corpo.form.StaffForm;
import com.mm.bean.ServiceBean;
import com.mm.core.master.StaffDao;
import com.mm.core.resource.LoginHelper;

/** 
 * MyEclipse Struts
 * Creation date: 10-09-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class StaffManageAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		System.out.println("In execute Staff Manage Action 18092009");
		HttpSession session = request.getSession();
		StaffForm staffForm = (StaffForm) form;
		StaffDao staffDao = new StaffDao();
		DataSource dataSource = getDataSource(request, "corpo");
		String operation = request.getParameter("operation");
		
		String month = request.getParameter("month");
		String year = request.getParameter("year");
		
		
		String forward = "showSchedule";
		int facilityId = (session.getAttribute("fId")!=null) ? Integer.parseInt((String)session.getAttribute("fId")) : 0;
		staffForm.setFacilityId(facilityId);
		
		System.out.println("operation->"+operation);
		System.out.println("operation 18092009->"+staffForm.getOperation());
		
		request.setAttribute("facilityId", facilityId);
		if (operation == null) {
			operation = staffForm.getOperation();
		}
		if (operation == null) {
			operation = "";
		}
		
		
		
		try {
			if (operation.equals("addnew")) {
				String results = null;//validateServiceForm(staffForm);
				if (results != null) {
					request.setAttribute(APPConstant.MESSAGE, APPConstant.SERVICE_INSERT_FAILURE);
					forward = "addServiceFailure";
				}
				else {
					System.out.println("Ready To Insert....................");
					staffDao.insertScedule(dataSource, staffForm);
					Vector consumerList = staffDao.getScheduleList(dataSource, facilityId);
					System.out.println("consumerList in Staff Manage Action->"+consumerList);
					request.setAttribute(APPConstant.STAFF_LIST, consumerList);
					request.setAttribute(APPConstant.MESSAGE, APPConstant.INSERT_SUCCESS);
					forward = "showSchedule";
				}
			} else if (operation.equals("edit")) {
				//staffDao.updateService(dataSource, staffForm);
				Vector consumerList = staffDao.getScheduleList(dataSource, facilityId);
				request.setAttribute(APPConstant.STAFF_LIST, consumerList);
				request.setAttribute(APPConstant.MESSAGE, APPConstant.EDIT_SUCCESS);
				forward = "showSchedule"; 
			}else if (operation.equals("forwardToAddPage")) {
				forward = "addSchedule";
			} else if (operation.equals("forwardToEditPage")) {
				setDataForEditPage(request);
				forward = "editSchedule";
			} else if (operation.equals("delete")) {
				deleteConsumer(request, facilityId);
			} else if (operation.equals("showSchedule")) {
				Vector consumerList = staffDao.getScheduleList(dataSource, facilityId);
				System.out.println("consumerList in Staff Manage Action For Show->"+consumerList);
				request.setAttribute(APPConstant.STAFF_LIST, consumerList);
			}
		} catch (Exception exception) {
			exception.printStackTrace();
			request.setAttribute(APPConstant.MESSAGE,APPConstant.FAILURE_MESSAGE);
		}
		System.out.println("Return From Staff Manage Action in Initial ->"+forward);
		return mapping.findForward(forward);
	}


	private void deleteConsumer(HttpServletRequest request, int facilityId)
			throws Exception {
		DataSource dataSource = getDataSource(request, "corpo");
		String serviceIds = request.getParameter("serviceIds");
		String serviceIdsArr[] = serviceIds.split(",");
		StaffDao staffDao = new StaffDao();
		staffDao.inactiveService(dataSource, serviceIdsArr);
		Vector consumerList = staffDao.getScheduleList(dataSource, facilityId);
		request.setAttribute(APPConstant.STAFF_LIST, consumerList);
		request.setAttribute(APPConstant.MESSAGE, APPConstant.DELETE_SUCCESS);
	}

	private void setDataForEditPage(HttpServletRequest request)
			throws Exception {
		StaffDao staffDao = new StaffDao();
		DataSource dataSource = getDataSource(request, "corpo");
		int serviceId = Integer.parseInt((String)request.getParameter("serviceId"));
		System.out.println("In Staff Manage Action-->"+serviceId);
	//	ServiceBean bean = staffDao.getServiceData(dataSource, serviceId);
		//request.setAttribute(APPConstant.SERVICEDATA, bean);
	}
	
	private String validateServiceForm(StaffForm staffForm ) {
		
		if (staffForm == null) {
			return "Please fill New Service form";
		}
		else if (staffForm.getServiceName() == null ||  staffForm.getServiceName().trim().length() <= 0) {
				return "Service Name cannot be empty";
			}
		else if(staffForm.getServiceDesc()==null || staffForm.getServiceDesc().trim().length()<=0){
				return "Service Description can not be empty";
		}
		
		
		return null;
		
	}
	
	
	/**
	 * date help function
	 * @param str_date
	 * @return
	 * @throws Exception
	 */
	private Date getDate(String str_date) throws Exception {
		DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
		Date sqlDate = new java.sql.Date(formatter.parse(str_date).getTime());
		return sqlDate;
	}
	
	/**
	 * Date Help function
	 * @param month
	 * @param year
	 * @return
	 * @throws Exception
	 */
	private Date getDate(int month,int year) throws Exception {
		String billMonth = "";
		if(month<10){
			billMonth = "0"+month;
		}else{
			billMonth = String.valueOf(month);
		}
		String str_date = "01/"+billMonth+"/"+year;
		DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
		Date sqlDate = new java.sql.Date(formatter.parse(str_date).getTime());
		return sqlDate;
	}
	
	public int getFacilityId(HttpSession session) {
		if(session.getAttribute(APPConstant.USER_INFORMATION) == null){
			return 1;
		}
		LoginHelper helper = (LoginHelper) session
				.getAttribute(APPConstant.USER_INFORMATION);
		return helper.getFacilityId();
	}
	public int getConsumerId(HttpSession session) {
		if(session.getAttribute(APPConstant.USER_INFORMATION) == null){
			return -1;
		}
		LoginHelper helper = (LoginHelper) session
				.getAttribute(APPConstant.USER_INFORMATION);
		return helper.getConsumerId();
	}
	
	public String getLoginName(HttpSession session) {
		if(session.getAttribute(APPConstant.USER_INFORMATION) == null){
			return "";
		}
		LoginHelper helper = (LoginHelper) session
				.getAttribute(APPConstant.USER_INFORMATION);
		return helper.getUserName();
	}
}
