/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.corpo.action;

import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.commons.dbcp.DataSourceConnectionFactory;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mm.resource.APPConstant;
import com.mm.struts.corpo.form.StaffPayrollForm;
import com.mm.bean.StaffPayrollBean;
import com.mm.core.master.StaffPayrollDao;
import com.mm.core.resource.LoginHelper;

/** 
 * MyEclipse Struts
 * Creation date: 10-09-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class StaffPayrollAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response) {
		System.out.println("In execute Staff PayRoll Action");
		HttpSession session = request.getSession();
		StaffPayrollForm staffPayrollForm = (StaffPayrollForm) form;
		StaffPayrollDao staffPayrollDao = new StaffPayrollDao();
		DataSource dataSource = getDataSource(request, "corpo");
		String operation = request.getParameter("operation");
		String staffId = request.getParameter("staffId");
		
		//System.out.println("staffId in Staff PayRoll Master->"+staffId);
		
		String month = request.getParameter("month");
		String year = request.getParameter("year");
		
		
		String forward = "showStaffPayroll";
		int facilityId = (session.getAttribute("fId")!=null) ? Integer.parseInt((String)session.getAttribute("fId")) : 0;
		staffPayrollForm.setFacilityId(facilityId);
		
		System.out.println("operation in Staff PayRoll Master->"+operation);
		System.out.println("operation->"+staffPayrollForm.getOperation());
		
		request.setAttribute("facilityId", facilityId);
		if (operation == null) {
			operation = staffPayrollForm.getOperation();
		}
		if (operation == null) {
			operation = "";
		}
		
		
		
		try {
			if (operation.equals("addnew")) {
				String results = null;//validateServiceForm(staffMasterForm);
				if (results != null) {
					request.setAttribute(APPConstant.MESSAGE, APPConstant.SERVICE_INSERT_FAILURE);
					forward = "addServiceFailure";
				}
				else {
					System.out.println("Ready To Insert....................Staff Payroll Form");
					//staffPayrollDao.insertDetail(dataSource, staffPayrollForm);
					Vector payrollList = staffPayrollDao.getStaffForPayroll(dataSource, facilityId);
					System.out.println("payrollList in Staff Master Action->"+payrollList);
					request.setAttribute(APPConstant.PAYROLLIST, payrollList);
					request.setAttribute(APPConstant.MESSAGE, APPConstant.INSERT_SUCCESS);
					forward = "showStaffPayroll";
				}
			} else if (operation.equals("edit")) {
				System.out.println("Ready To Update....................Staff Master Form");
				//staffPayrollDao.updateService(dataSource, staffMasterForm);
				staffPayrollDao.updateStaffPayroll(dataSource, staffPayrollForm);
				Vector consumerList = staffPayrollDao.getStaffForPayroll(dataSource, facilityId);
				request.setAttribute(APPConstant.STAFF_LIST, consumerList);
				request.setAttribute(APPConstant.MESSAGE, APPConstant.EDIT_SUCCESS);
				forward = "showStaffPayroll"; 
			}else if (operation.equals("billGeneration")) {

				int billMonth = staffPayrollForm.getBillMonth();
				int billYear = staffPayrollForm.getBillYear();
				Date billDate = getDate(billMonth,billYear);
				
				String dueDate = request.getParameter("dueDateStr");
				Date date = getDate(dueDate);
				System.out.println("Billmonth & year"+ "="+billMonth+" & "+ billYear );
				if (billMonth !=0  && billYear!=0 ){
					staffPayrollDao.generateConsumerBills(dataSource, facilityId, billMonth, billYear, date);
					forward = "showStaffPayroll";  // need to change the follow-up page
				}
				else {
					request.setAttribute(APPConstant.MESSAGE, "Month/Year cannot be BLANK!");
					forward = "showStaffPayroll";  // need to change the follow-up page
				}
				}
			
				
			else if (operation.equals("forwardToAddPage")) {
				System.out.println("In Staff Manage Action for adding->"+forward);
				forward = "addStaff";
			} else if (operation.equals("forwardToUpdatePage")) {
				setDataForEditPage(request);
				forward = "editPayroll";
			} else if (operation.equals("delete")) {
				deleteConsumer(request, facilityId);
			} else if (operation.equals("showStaffPayroll")) {
				System.out.println("Now operation->"+operation);
				Vector consumerList = staffPayrollDao.getStaffForPayroll(dataSource, facilityId);
				System.out.println("consumerList in Staff Manage Action->"+consumerList);
				
				request.setAttribute(APPConstant.STAFF_LIST, consumerList);
			}else if (operation.equals("searchService")){
				String serviceName=request.getParameter("serviceName"); 
				Vector consumerList = staffPayrollDao.searchServices(dataSource, serviceName);
				request.setAttribute(APPConstant.STAFF_LIST, consumerList);
			}else if (operation.equals("showServiceResident")){
				int consumerId = getConsumerId(session);
				//int facilityId = getFacilityId(session);
				String serviceName=request.getParameter("serviceName"); 
				Vector consumerList = staffPayrollDao.getServiceListResident(dataSource, consumerId, facilityId);
				request.setAttribute(APPConstant.STAFF_LIST, consumerList);
				forward = "showServiceResident";
			}
		} catch (Exception exception) {
			exception.printStackTrace();
			request.setAttribute(APPConstant.MESSAGE,APPConstant.FAILURE_MESSAGE);
		}
		System.out.println("Return From Staff Manage Action in Initial ->"+forward);
		return mapping.findForward(forward);
	}


	private void deleteConsumer(HttpServletRequest request, int facilityId)
			throws Exception {
		DataSource dataSource = getDataSource(request, "corpo");
		String serviceIds = request.getParameter("serviceIds");
		String serviceIdsArr[] = serviceIds.split(",");
		StaffPayrollDao staffPayrollDao = new StaffPayrollDao();
		staffPayrollDao.inactiveService(dataSource, serviceIdsArr);
		Vector consumerList = staffPayrollDao.getStaffForPayroll(dataSource, facilityId);
		request.setAttribute(APPConstant.STAFF_LIST, consumerList);
		request.setAttribute(APPConstant.MESSAGE, APPConstant.DELETE_SUCCESS);
	}

	private void setDataForEditPage(HttpServletRequest request)	throws Exception {
		
		StaffPayrollDao staffPayrollDao = new StaffPayrollDao();
		DataSource dataSource = getDataSource(request, "corpo");
		int staffId = Integer.parseInt((String)request.getParameter("staffId"));
		System.out.println("In staffId Manage Action-->"+staffId);
		StaffPayrollBean bean = staffPayrollDao.getPayrollData(dataSource, staffId);
		System.out.println("bean bean bean bean-->"+bean);
		request.setAttribute(APPConstant.PAYROLLDATA, bean);
		System.out.println("bean bean bean bean-->"+bean);
	}
	
	private String validateServiceForm(StaffPayrollForm staffMasterForm ) {
		
		if (staffMasterForm == null) {
			return "Please fill New Service form";
		}
		else if (staffMasterForm.getServiceName() == null ||  staffMasterForm.getServiceName().trim().length() <= 0) {
				return "Service Name cannot be empty";
			}
		else if(staffMasterForm.getServiceDesc()==null || staffMasterForm.getServiceDesc().trim().length()<=0){
				return "Service Description can not be empty";
		}
		
		
		return null;
		
	}
	
	
	/**
	 * date help function
	 * @param str_date
	 * @return
	 * @throws Exception
	 */
	private Date getDate(String str_date) throws Exception {
		DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
		Date sqlDate = new java.sql.Date(formatter.parse(str_date).getTime());
		return sqlDate;
	}
	
	/**
	 * Date Help function
	 * @param month
	 * @param year
	 * @return
	 * @throws Exception
	 */
	private Date getDate(int month,int year) throws Exception {
		String billMonth = "";
		if(month<10){
			billMonth = "0"+month;
		}else{
			billMonth = String.valueOf(month);
		}
		String str_date = "01/"+billMonth+"/"+year;
		DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
		Date sqlDate = new java.sql.Date(formatter.parse(str_date).getTime());
		return sqlDate;
	}
	
	public int getFacilityId(HttpSession session) {
		if(session.getAttribute(APPConstant.USER_INFORMATION) == null){
			return 1;
		}
		LoginHelper helper = (LoginHelper) session
				.getAttribute(APPConstant.USER_INFORMATION);
		return helper.getFacilityId();
	}
	public int getConsumerId(HttpSession session) {
		if(session.getAttribute(APPConstant.USER_INFORMATION) == null){
			return -1;
		}
		LoginHelper helper = (LoginHelper) session
				.getAttribute(APPConstant.USER_INFORMATION);
		return helper.getConsumerId();
	}
	
	public String getLoginName(HttpSession session) {
		if(session.getAttribute(APPConstant.USER_INFORMATION) == null){
			return "";
		}
		LoginHelper helper = (LoginHelper) session
				.getAttribute(APPConstant.USER_INFORMATION);
		return helper.getUserName();
	}
}
