/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.corpo.form;

import java.util.Vector;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;	
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.mm.struts.corpo.form.WriteQueryForm;
import com.mm.core.master.*;
import javax.sql.DataSource;
import java.util.*;

import org.apache.struts.validator.ValidatorForm;
/** 
 * MyEclipse Struts
 * Creation date: 20-06-2007
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class WriteQueryForm extends ValidatorForm
{
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** text property */
	/** currpass property */
	/** pass property */
	/** password property */
	
	private String blogTitle= "";
	private String qtype = "";
	private String blogtext = "";
	private String count = "";
	private String pagetype = "";
	private String strid = "";
	
	/*
	 * Generated Methods
	 */
	
	
	
	
	/** 
	 * Returns the currpass.
	 * @return String
	 */

	public String getBlogTitle() {
		return blogTitle;
	}
	/** 
	 * Set the currpass.
	 * @param currpass The currpass to set
	 */
	public void setBlogTitle(String blogTitle) {
		this.blogTitle = blogTitle;
	}
	/** 
	 * Returns the blogtext
	 * @return String
	 */

	public String getBlogtext() {
		return blogtext;
	}
	/** 
	 * Set the blogtext.
	 * @param blogtext The blogtext to set
	 */
	public void setBlogtext(String blogtext) {
		this.blogtext = blogtext;
	}
	/** 
	 * Returns the password.
	 * @return String
	 */

	public String getQtype() {
		return qtype;
	}
	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setQtype(String qtype) {
		this.qtype = qtype;
	}
	/** 
	 * Returns the userId.
	 * @return String
	 */
	/** 
	 * Returns the count.
	 * @return String
	 */

	public String getCount() {
		return count;
	}
	/** 
	 * Set the count.
	 * @param count The count to set
	 */
	public void setCount(String count) {
		this.count = count;
	}

	/** 
	 * Returns the pagetype.
	 * @return String
	 */

	public String getPagetype() {
		return pagetype;
	}
	/** 
	 * Set the pagetype.
	 * @param pagetype The pagetype to set
	 */
	public void setPagetype(String pagetype) {
		this.pagetype = pagetype;
	}
	
	/** 
	 * Returns the strid.
	 * @return String
	 */

	public String getStrid() {
		return strid;
	}
	/** 
	 * Set the strid.
	 * @param strid The strid to set
	 */
	public void setStrid(String strid) {
		this.strid = strid;
	}
	
	/** cmbDate property */
	private String cmbDatestart = "";
	
	/** 
	 * Returns the cmbDate.
	 * @return String
	 */
	public String getCmbDatestart() {
		return this.cmbDatestart;
	}
	/** 
	 * Set the cmbDate.
	 * @param cmbDate The cmbDate to set
	 */
	public void setCmbDatestart(String cmbDatestart) {
		this.cmbDatestart = cmbDatestart;
	}
	
	
	/** cmbMonth property */
	private String cmbMonthstart = "";
	/** 
	 * Returns the cmbMonth.
	 * @return String
	 */
	public String getCmbMonthstart() {
		return this.cmbMonthstart;
	}

	/** 
	 * Set the cmbMonth.
	 * @param cmbMonth The cmbMonth to set
	 */
	public void setCmbMonthstart(String cmbMonthstart) {
		this.cmbMonthstart = cmbMonthstart;
	}
	
	
	/** cmbYear property */
	private String cmbYearstart = "";
	/** 
	 * Returns the cmbYear.
	 * @return String
	 */
	public String getCmbYearstart() {
		return this.cmbYearstart;
	}
	/** 
	 * Set the cmbYear.
	 * @param cmbYear The cmbYear to set
	 */
	public void setCmbYearstart(String cmbYearstart) {
		this.cmbYearstart = cmbYearstart;
	}
	
				/**EndDate Detail Start**/

	/** cmbDate property */
	private String cmbDateend = "";
	
	/** 
	 * Returns the cmbDate.
	 * @return String
	 */
	public String getCmbDateend() {
		return this.cmbDateend;
	}
	/** 
	 * Set the cmbDate.
	 * @param cmbDate The cmbDate to set
	 */
	public void setCmbDateend(String cmbDateend) {
		this.cmbDateend = cmbDateend;
	}
	
	
	/** cmbMonth property */
	private String cmbMonthend = "";
	/** 
	 * Returns the cmbMonth.
	 * @return String
	 */
	public String getCmbMonthend() {
		return this.cmbMonthend;
	}

	/** 
	 * Set the cmbMonth.
	 * @param cmbMonth The cmbMonth to set
	 */
	public void setCmbMonthend(String cmbMonthend) {
		this.cmbMonthend = cmbMonthend;
	}
	
	
	/** cmbYear property */
	private String cmbYearend = "";
	/** 
	 * Returns the cmbYear.
	 * @return String
	 */
	public String getCmbYearend() {
		return this.cmbYearend;
	}
	/** 
	 * Set the cmbYear.
	 * @param cmbYear The cmbYear to set
	 */
	public void setCmbYearend(String cmbYearend) {
		this.cmbYearend = cmbYearend;
	}
					/**enddate Details End**/

	 

}	