
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.student.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.mm.struts.student.form.PersonalityTestForm;

import java.text.SimpleDateFormat;
import java.util.StringTokenizer;
import java.util.Vector;

import com.mm.core.master.*;
import com.mm.core.resource.Constant;
import com.mm.core.resource.MailText;
import com.mm.core.resource.Resource;

import javax.sql.DataSource;

/** 
 * MyEclipse Struts
 * Creation date: 06-19-2007
 * 
 * XDoclet definition:
 * @struts.action path="/changepass" name="ChangepassForm" input="/form/Changepass.jsp" scope="request" 
 * @struts.action-forward name="success" path="changepass.jsp"
 */
public class PersonalityTestAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,HttpServletRequest request, HttpServletResponse response) {
		
		PersonalityTestForm personalityTestForm = (PersonalityTestForm) form;// TODO Auto-generated method stub
		
		PersonalityTestForm setValuePersonalityTestForm = new PersonalityTestForm();
		
			Vector <String> datavec = new Vector<String>();		
			DataSource ds = getDataSource(request,"student");
			IndvMaster indvMaster = new IndvMaster();
			RootMaster rootMaster = new RootMaster();
			
			 String result = "failure";
			////////System.out.println("....llllllllllllll........");
			
			int testId = (request.getParameter("testId")!=null) ? Integer.parseInt(request.getParameter("testId")) : 0;
			
			////////System.out.println("testId...Action..."+testId);
			
			String testId1 = personalityTestForm.getTestId().toString();			
			////System.out.println("testId1..PersonalityTestAction...."+testId1);
			
			HttpSession session = request.getSession();
			String uId = (String)session.getAttribute("uId");
			
			Vector <String> datavec1 = new Vector<String>();	
			datavec1.add(String.valueOf("0"));	
            datavec1.add(String.valueOf("20"));	
	        datavec1.add(uId);	     
	        
	        Vector testTypeVec = rootMaster.getTestType(ds, testId1);	
	        ////System.out.println("testTypeVec..PersonalityTestAction...."+testTypeVec);
	        
	        String testType = testTypeVec.elementAt(0).toString();
	        String testName = testTypeVec.elementAt(1).toString();
	        String totalMarks = testTypeVec.elementAt(2).toString();
	        
	        int flag = 0;
	        String analysis = "";
	        
	        String tansStr1 = "";
			int tansInt1 = 0;
			String tansStr2 = "";
			int tansInt2 = 0;
			String tansStr3 = "";
			int tansInt3 = 0;
			String tansStr4 = "";
			int tansInt4 = 0;
			String tansStr5 = "";
			int tansInt5 = 0;
			String tansStr6 = "";
			int tansInt6 = 0;
			String tansStr7 = "";
			int tansInt7 = 0;
			String tansStr8 = "";
			int tansInt8 = 0;
			String tansStr9 = "";
			int tansInt9 = 0;
			String tansStr10 = "";
			int tansInt10 = 0;
			
			String tansStr11 = "";
			int tansInt11 = 0;
			String tansStr12 = "";
			int tansInt12 = 0;
			String tansStr13 = "";
			int tansInt13 = 0;
			String tansStr14 = "";
			int tansInt14 = 0;
			String tansStr15 = "";
			int tansInt15 = 0;
			String tansStr16 = "";
			int tansInt16 = 0;
			String tansStr17 = "";
			int tansInt17 = 0;
			String tansStr18 = "";
			int tansInt18 = 0;
			String tansStr19 = "";
			int tansInt19 = 0;
			String tansStr20 = "";
			int tansInt20 = 0;
			
			String tansStr21 = "";
			int tansInt21 = 0;
			String tansStr22 = "";
			int tansInt22 = 0;
			String tansStr23 = "";
			int tansInt23 = 0;
			String tansStr24 = "";
			int tansInt24 = 0;
			String tansStr25 = "";
			int tansInt25 = 0;
			String tansStr26 = "";
			int tansInt26 = 0;
			String tansStr27 = "";
			int tansInt27 = 0;
			String tansStr28 = "";
			int tansInt28 = 0;
			String tansStr29 = "";
			int tansInt29 = 0;
			String tansStr30 = "";
			int tansInt30 = 0;
			
			String tansStr31 = "";
			int tansInt31 = 0;
			String tansStr32 = "";
			int tansInt32 = 0;
			String tansStr33 = "";
			int tansInt33 = 0;
			String tansStr34 = "";
			int tansInt34 = 0;
			String tansStr35 = "";
			int tansInt35 = 0;
	        
	         String[] tans1 = personalityTestForm.getField1();	         
	         String[] tans2 = personalityTestForm.getField2();
	         String[] tans3 = personalityTestForm.getField3();
	         String[] tans4 = personalityTestForm.getField4();	 
	         String[] tans5 = personalityTestForm.getField5();	 
	         String[] tans6 = personalityTestForm.getField6();	 
	         String[] tans7 = personalityTestForm.getField7();	 
	         String[] tans8 = personalityTestForm.getField8();	 
	         String[] tans9 = personalityTestForm.getField9();	 
	         String[] tans10 = personalityTestForm.getField10();	
	         
	         String[] tans11 = personalityTestForm.getField11();	         
	         String[] tans12 = personalityTestForm.getField12();
	         String[] tans13 = personalityTestForm.getField13();
	         String[] tans14 = personalityTestForm.getField14();	 
	         String[] tans15 = personalityTestForm.getField15();	 
	         String[] tans16 = personalityTestForm.getField16();	 
	         String[] tans17 = personalityTestForm.getField17();	 
	         String[] tans18 = personalityTestForm.getField18();	 
	         String[] tans19 = personalityTestForm.getField19();	 
	         String[] tans20 = personalityTestForm.getField20();
	         
	         String[] tans21 = personalityTestForm.getField21();	         
	         String[] tans22 = personalityTestForm.getField22();
	         String[] tans23 = personalityTestForm.getField23();
	         String[] tans24 = personalityTestForm.getField24();	 
	         String[] tans25 = personalityTestForm.getField25();	 
	         String[] tans26 = personalityTestForm.getField26();	 
	         String[] tans27 = personalityTestForm.getField27();	 
	         String[] tans28 = personalityTestForm.getField28();	 
	         String[] tans29 = personalityTestForm.getField29();	 
	         String[] tans30 = personalityTestForm.getField30();	
				
	         String[] tans31 = personalityTestForm.getField31();	         
	         String[] tans32 = personalityTestForm.getField32();
	         String[] tans33 = personalityTestForm.getField33();
	         String[] tans34 = personalityTestForm.getField34();	 
	         String[] tans35 = personalityTestForm.getField35();	 
	        
        	
	        // ////System.out.println("In 1>>>>>>>>>>>>"+tans1[0]);
	       //  ////System.out.println("In tans35>>>>>>>>>>>>"+tans35);
        	
        	
	        
        	
        	 if(testType.equalsIgnoreCase("Digital")){
        		 
        		 
        		 //////System.out.println("In Digital>>>>>>>>>>>>");
        		 
        		if(tans1!=null)
        		{
        		 for(int i=0; i<tans1.length; i++)
					{												
						if(tans1[i].toString()!=null){
							
							tansInt1 = tansInt1 + Integer.parseInt(tans1[i]);
						}
					}
        		}
					
        		if(tans2!=null)
        		{
				for(int i=0; i<tans2.length; i++)
				{										
					if(tans2[i].toString()!=null){
						
						tansInt2 = tansInt2 + Integer.parseInt(tans2[i]);
					}
				}
        		}
        		if(tans3!=null)
        		{
				for(int i=0; i<tans3.length; i++)
				{										
					if(tans3[i].toString()!=null){
						
						tansInt3 = tansInt3 + Integer.parseInt(tans3[i]);
					}
				}
        		}
        		if(tans4!=null)
        		{
				for(int i=0; i<tans4.length; i++)
				{										
					if(tans4[i].toString()!=null){
						
						tansInt4 = tansInt4 + Integer.parseInt(tans4[i]);
					}
				}
        		}
        		if(tans5!=null)
        		{
        		
				for(int i=0; i<tans5.length; i++)
				{										
					if(tans5[i].toString()!=null){
						
						tansInt5 = tansInt5 + Integer.parseInt(tans5[i]);
					}
				}
        		}
        		if(tans6!=null)
        		{
				for(int i=0; i<tans6.length; i++)
				{										
					if(tans6[i].toString()!=null){
						
						tansInt6 = tansInt6 + Integer.parseInt(tans6[i]);
					}
				}
        		}
        		if(tans7!=null)
        		{
				for(int i=0; i<tans7.length; i++)
				{										
					if(tans7[i].toString()!=null){
						
						tansInt7 = tansInt7 + Integer.parseInt(tans7[i]);
					}
				}
        		}
        		if(tans8!=null)
        		{
				for(int i=0; i<tans8.length; i++)
				{										
					if(tans8[i].toString()!=null){
						
						tansInt8 = tansInt8 + Integer.parseInt(tans8[i]);
					}
				}
        		}
        		if(tans9!=null)
        		{
				for(int i=0; i<tans9.length; i++)
				{										
					if(tans9[i].toString()!=null){
						
						tansInt9 = tansInt9 + Integer.parseInt(tans9[i]);
					}
				}
        		}
        		if(tans10!=null)
        		{
				for(int i=0; i<tans10.length; i++)
				{										
					if(tans10[i].toString()!=null){
						
						tansInt10 = tansInt10 + Integer.parseInt(tans10[i]);
					}
				}
        		}
        		if(tans11!=null)
        		{
				 for(int i=0; i<tans11.length; i++)
					{												
						if(tans11[i].toString()!=null){
							
							tansInt11 = tansInt11 + Integer.parseInt(tans11[i]);
						}
					}
        		}
        		if(tans12!=null)
        		{	
			
				for(int i=0; i<tans12.length; i++)
				{										
					if(tans12[i].toString()!=null){
						
						tansInt12 = tansInt12 + Integer.parseInt(tans12[i]);
					}
				}
        		}
        		if(tans13!=null)
        		{
				for(int i=0; i<tans13.length; i++)
				{										
					if(tans13[i].toString()!=null){
						
						tansInt13 = tansInt13 + Integer.parseInt(tans13[i]);
					}
				}
        		}
        		if(tans14!=null)
        		{
				for(int i=0; i<tans14.length; i++)
				{										
					if(tans14[i].toString()!=null){
						
						tansInt14 = tansInt14 + Integer.parseInt(tans14[i]);
					}
				}
        		}
        		if(tans15!=null)
        		{
				for(int i=0; i<tans15.length; i++)
				{										
					if(tans15[i].toString()!=null){
						
						tansInt15 = tansInt15 + Integer.parseInt(tans15[i]);
					}
				}
        		}
        		if(tans16!=null)
        		{
				for(int i=0; i<tans16.length; i++)
				{										
					if(tans16[i].toString()!=null){
						
						tansInt16 = tansInt16 + Integer.parseInt(tans16[i]);
					}
				}
        		}
        		if(tans17!=null)
        		{
				for(int i=0; i<tans17.length; i++)
				{										
					if(tans17[i].toString()!=null){
						
						tansInt17 = tansInt17 + Integer.parseInt(tans17[i]);
					}
				}
        		}
        		if(tans18!=null)
        		{
				for(int i=0; i<tans18.length; i++)
				{										
					if(tans18[i].toString()!=null){
						
						tansInt18 = tansInt18 + Integer.parseInt(tans18[i]);
					}
				}
        		}
        		if(tans19!=null)
        		{
				for(int i=0; i<tans19.length; i++)
				{										
					if(tans19[i].toString()!=null){
						
						tansInt19 = tansInt19 + Integer.parseInt(tans19[i]);
					}
				}
        		}
        		if(tans20!=null)
        		{
				for(int i=0; i<tans20.length; i++)
				{										
					if(tans20[i].toString()!=null){
						
						tansInt20 = tansInt20 + Integer.parseInt(tans20[i]);
					}
				}
        		}
        		if(tans21!=null)
        		{
				 for(int i=0; i<tans21.length; i++)
					{												
						if(tans21[i].toString()!=null){
							
							tansInt21 = tansInt21 + Integer.parseInt(tans21[i]);
						}
					}
					
        		}
        		if(tans22!=null)
        		{
				for(int i=0; i<tans22.length; i++)
				{										
					if(tans22[i].toString()!=null){
						
						tansInt22 = tansInt22 + Integer.parseInt(tans22[i]);
					}
				}
        		}
        		if(tans23!=null)
        		{
				for(int i=0; i<tans23.length; i++)
				{										
					if(tans23[i].toString()!=null){
						
						tansInt23 = tansInt23 + Integer.parseInt(tans23[i]);
					}
				}
        		}
        		if(tans24!=null)
        		{
				for(int i=0; i<tans24.length; i++)
				{										
					if(tans24[i].toString()!=null){
						
						tansInt24 = tansInt24 + Integer.parseInt(tans24[i]);
					}
				}
        		}
        		if(tans25!=null)
        		{
				for(int i=0; i<tans25.length; i++)
				{										
					if(tans25[i].toString()!=null){
						
						tansInt25 = tansInt25 + Integer.parseInt(tans25[i]);
					}
				}
        		}
        		if(tans26!=null)
        		{
				for(int i=0; i<tans26.length; i++)
				{										
					if(tans26[i].toString()!=null){
						
						tansInt26 = tansInt26 + Integer.parseInt(tans26[i]);
					}
				}
        		}
        		if(tans27!=null)
        		{
				for(int i=0; i<tans27.length; i++)
				{										
					if(tans27[i].toString()!=null){
						
						tansInt27 = tansInt27 + Integer.parseInt(tans27[i]);
					}
				}
        		}
        		if(tans28!=null)
        		{
				for(int i=0; i<tans28.length; i++)
				{										
					if(tans28[i].toString()!=null){
						
						tansInt28 = tansInt28 + Integer.parseInt(tans28[i]);
					}
				}
        		}
        		if(tans29!=null)
        		{
				for(int i=0; i<tans29.length; i++)
				{										
					if(tans29[i].toString()!=null){
						
						tansInt29 = tansInt29 + Integer.parseInt(tans29[i]);
					}
				}
        		}
        		if(tans30!=null)
        		{
				for(int i=0; i<tans30.length; i++)
				{										
					if(tans30[i].toString()!=null){
						
						tansInt30 = tansInt30 + Integer.parseInt(tans30[i]);
					}
				}
        		}
        		if(tans31!=null)
        		{
				for(int i=0; i<tans31.length; i++)
				{												
					if(tans31[i].toString()!=null){
						
						tansInt31 = tansInt31 + Integer.parseInt(tans31[i]);
					}
				}
				
        		}
        		if(tans32!=null)
        		{
			for(int i=0; i<tans32.length; i++)
			{										
				if(tans32[i].toString()!=null){
					
					tansInt32 = tansInt32 + Integer.parseInt(tans32[i]);
				}
			}
        		}
        		if(tans33!=null)
        		{
			for(int i=0; i<tans33.length; i++)
			{										
				if(tans33[i].toString()!=null){
					
					tansInt33 = tansInt33 + Integer.parseInt(tans33[i]);
				}
			}
        		}
        		if(tans34!=null)
        		{
			for(int i=0; i<tans34.length; i++)
			{										
				if(tans34[i].toString()!=null){
					
					tansInt34 = tansInt34 + Integer.parseInt(tans34[i]);
				}
			}
        		}
        		if(tans35!=null)
        		{
			for(int i=0; i<tans35.length; i++)
			{										
				if(tans35[i].toString()!=null){
					
					tansInt35 = tansInt35 + Integer.parseInt(tans35[i]);
				}
			}
        		}
				
        		 
        		int obtained_marks = (tansInt1+tansInt2+tansInt3+tansInt4+tansInt5+tansInt6+tansInt7+tansInt8+tansInt9+tansInt10+tansInt11+tansInt12+tansInt13+tansInt14+tansInt15+tansInt16+tansInt17+tansInt18+tansInt19+tansInt20+tansInt21+tansInt22+tansInt23+tansInt24+tansInt25+tansInt26+tansInt27+tansInt28+tansInt29+tansInt30+tansInt31+tansInt32+tansInt33+tansInt34+tansInt35);        		 
        		 
        		java.util.Date dt = new java.util.Date();
 				SimpleDateFormat sform = new SimpleDateFormat("yyyy-MM-dd, HH:mm:ss,a");
 				String completeRemDate = sform.format(dt);
 				StringTokenizer sttotal = new StringTokenizer(completeRemDate, ",");
 			    String creationDate = sttotal.nextToken();
 			    
 	        	datavec.add(String.valueOf(testId));
 		        datavec.add(uId);		     
 		        datavec.add(totalMarks);
 		        datavec.add(String.valueOf(obtained_marks));
 		        datavec.add(analysis); 
 		        datavec.add(testName);
 		        datavec.add(creationDate);
 		        datavec.add("0");
 		        
 		       // System.out.println("datavecdatavecdatavec>>>>>>>"+datavec);
 		        
 		       result = indvMaster.setTestVec(ds, datavec);
		        //////System.out.println("resultresultresult>>>>>>>"+result);
        }	        
	    if(testType.equalsIgnoreCase("Enneagram")){
	   
		if(tans1!=null)
		{														
        	for(int i=0; i<tans1.length; i++)
			{
				
				if(i!=(tans1.length-1))
					tansStr1 = tansStr1+tans1[i]+",";
				else
				{
					tansStr1 = tansStr1+tans1[i];
				}
				
			}
		}
		if(tans2!=null)
		{	
			for(int i=0; i<tans2.length; i++)
			{
				
				if(i!=(tans2.length-1))
					tansStr2 = tansStr2+tans2[i]+",";
				else
				{
					tansStr2 = tansStr2+tans2[i];
				}
				
			}
		}
		if(tans3!=null)
		{
			for(int i=0; i<tans3.length; i++)
			{
				
				if(i!=(tans3.length-1))
					tansStr3 = tansStr3+tans3[i]+",";
				else
				{
					tansStr3 = tansStr3+tans3[i];
				}
				
			}
		}
		if(tans4!=null)
		{
			for(int i=0; i<tans4.length; i++)
			{
				
				if(i!=(tans4.length-1))
					tansStr4 = tansStr4+tans4[i]+",";
				else
				{
					tansStr4 = tansStr4+tans4[i];
				}
				
			}
		}
		if(tans5!=null)
		{
			for(int i=0; i<tans5.length; i++)
			{
				
				if(i!=(tans5.length-1))
					tansStr5 = tansStr5+tans5[i]+",";
				else
				{
					tansStr5 = tansStr5+tans5[i];
				}
				
			}
		}
		if(tans6!=null)
		{
			for(int i=0; i<tans6.length; i++)
			{
				
				if(i!=(tans6.length-1))
					tansStr6 = tansStr6+tans6[i]+",";
				else
				{
					tansStr6 = tansStr6+tans6[i];
				}
				
			}
		}
		if(tans7!=null)
		{
			for(int i=0; i<tans7.length; i++)
			{
				
				if(i!=(tans7.length-1))
					tansStr7 = tansStr7+tans7[i]+",";
				else
				{
					tansStr7 = tansStr7+tans7[i];
				}
				
			}
		}
		if(tans8!=null)
		{
			for(int i=0; i<tans8.length; i++)
			{
				
				if(i!=(tans8.length-1))
					tansStr8 = tansStr8+tans8[i]+",";
				else
				{
					tansStr8 = tansStr8+tans8[i];
				}
				
			}
		}
		if(tans9!=null)
		{
			for(int i=0; i<tans9.length; i++)
			{
				
				if(i!=(tans9.length-1))
					tansStr9 = tansStr9+tans9[i]+",";
				else
				{
					tansStr9 = tansStr9+tans9[i];
				}
				
			}
		}
		if(tans10!=null)
		{
			for(int i=0; i<tans10.length; i++)
			{
				
				if(i!=(tans10.length-1))
					tansStr10 = tansStr10+tans10[i]+",";
				else
				{
					tansStr10 = tansStr10+tans10[i];
				}
				
			}
		}
		if(tans11!=null)
		{
			for(int i=0; i<tans11.length; i++)
			{
				
				if(i!=(tans11.length-1))
					tansStr11 = tansStr11+tans11[i]+",";
				else
				{
					tansStr1 = tansStr11+tans11[i];
				}
				
			}
		}
		if(tans12!=null)
		{	
			for(int i=0; i<tans12.length; i++)
			{
				
				if(i!=(tans12.length-1))
					tansStr12 = tansStr2+tans12[i]+",";
				else
				{
					tansStr12 = tansStr12+tans12[i];
				}
				
			}
		}
		if(tans13!=null)
		{
			for(int i=0; i<tans13.length; i++)
			{
				
				if(i!=(tans13.length-1))
					tansStr13 = tansStr13+tans13[i]+",";
				else
				{
					tansStr13 = tansStr13+tans13[i];
				}
				
			}
		}
		if(tans14!=null)
		{
			for(int i=0; i<tans14.length; i++)
			{
				
				if(i!=(tans14.length-1))
					tansStr14 = tansStr14+tans14[i]+",";
				else
				{
					tansStr14 = tansStr14+tans14[i];
				}
				
			}
		}
		if(tans15!=null)
		{
			for(int i=0; i<tans15.length; i++)
			{
				
				if(i!=(tans15.length-1))
					tansStr15 = tansStr15+tans15[i]+",";
				else
				{
					tansStr15 = tansStr15+tans15[i];
				}
				
			}
		}
		if(tans16!=null)
		{
			for(int i=0; i<tans16.length; i++)
			{
				
				if(i!=(tans16.length-1))
					tansStr16 = tansStr16+tans16[i]+",";
				else
				{
					tansStr16 = tansStr16+tans16[i];
				}
				
			}
		}
		if(tans17!=null)
		{
			for(int i=0; i<tans17.length; i++)
			{
				
				if(i!=(tans17.length-1))
					tansStr17 = tansStr17+tans17[i]+",";
				else
				{
					tansStr17 = tansStr17+tans17[i];
				}
				
			}
		}
		if(tans18!=null)
		{
			for(int i=0; i<tans18.length; i++)
			{
				
				if(i!=(tans18.length-1))
					tansStr18 = tansStr18+tans18[i]+",";
				else
				{
					tansStr18 = tansStr18+tans18[i];
				}
				
			}
		}
		if(tans19!=null)
		{
			for(int i=0; i<tans19.length; i++)
			{
				
				if(i!=(tans19.length-1))
					tansStr19 = tansStr19+tans19[i]+",";
				else
				{
					tansStr19 = tansStr19+tans19[i];
				}
				
			}
		}
		if(tans20!=null)
		{
			for(int i=0; i<tans20.length; i++)
			{
				
				if(i!=(tans20.length-1))
					tansStr20 = tansStr20+tans20[i]+",";
				else
				{
					tansStr20 = tansStr20+tans20[i];
				}
				
			}
		}
		if(tans21!=null)
		{
			for(int i=0; i<tans21.length; i++)
			{
				
				if(i!=(tans21.length-1))
					tansStr21 = tansStr21+tans23[i]+",";
				else
				{
					tansStr21 = tansStr21+tans23[i];
				}
				
			}
		}
		if(tans22!=null)
		{	
			for(int i=0; i<tans22.length; i++)
			{
				
				if(i!=(tans22.length-1))
					tansStr22 = tansStr22+tans22[i]+",";
				else
				{
					tansStr22 = tansStr22+tans22[i];
				}
				
			}
		}
		if(tans23!=null)
		{
			for(int i=0; i<tans23.length; i++)
			{
				
				if(i!=(tans23.length-1))
					tansStr23 = tansStr23+tans23[i]+",";
				else
				{
					tansStr23 = tansStr23+tans23[i];
				}
				
			}
		}
		if(tans24!=null)
		{
			for(int i=0; i<tans24.length; i++)
			{
				
				if(i!=(tans24.length-1))
					tansStr24 = tansStr24+tans24[i]+",";
				else
				{
					tansStr24 = tansStr24+tans24[i];
				}
				
			}
		}
		if(tans25!=null)
		{
			for(int i=0; i<tans25.length; i++)
			{
				
				if(i!=(tans25.length-1))
					tansStr25 = tansStr25+tans25[i]+",";
				else
				{
					tansStr25 = tansStr25+tans25[i];
				}
				
			}
		}
		if(tans26!=null)
		{
			for(int i=0; i<tans26.length; i++)
			{
				
				if(i!=(tans26.length-1))
					tansStr26 = tansStr26+tans26[i]+",";
				else
				{
					tansStr26 = tansStr2+tans26[i];
				}
				
			}
		}
		if(tans27!=null)
		{
			for(int i=0; i<tans27.length; i++)
			{
				
				if(i!=(tans27.length-1))
					tansStr27 = tansStr27+tans27[i]+",";
				else
				{
					tansStr27 = tansStr27+tans27[i];
				}
				
			}
		}
		if(tans28!=null)
		{
			for(int i=0; i<tans28.length; i++)
			{
				
				if(i!=(tans28.length-1))
					tansStr28 = tansStr28+tans28[i]+",";
				else
				{
					tansStr28 = tansStr28+tans28[i];
				}
				
			}
		}
		if(tans29!=null)
		{
			for(int i=0; i<tans29.length; i++)
			{
				
				if(i!=(tans29.length-1))
					tansStr29 = tansStr29+tans29[i]+",";
				else
				{
					tansStr29 = tansStr29+tans29[i];
				}
				
			}
		}
		if(tans30!=null)
		{
			for(int i=0; i<tans30.length; i++)
			{
				
				if(i!=(tans30.length-1))
					tansStr30 = tansStr30+tans30[i]+",";
				else
				{
					tansStr30 = tansStr30+tans30[i];
				}
				
			}
		}
		if(tans31!=null)
		{
			for(int i=0; i<tans31.length; i++)
			{
				
				if(i!=(tans31.length-1))
					tansStr31 = tansStr31+tans31[i]+",";
				else
				{
					tansStr31 = tansStr13+tans31[i];
				}
				
			}
		}
		if(tans32!=null)
		{	
			for(int i=0; i<tans32.length; i++)
			{
				
				if(i!=(tans32.length-1))
					tansStr32 = tansStr32+tans32[i]+",";
				else
				{
					tansStr32 = tansStr32+tans32[i];
				}
				
			}
		}
		if(tans33!=null)
		{
			for(int i=0; i<tans33.length; i++)
			{
				
				if(i!=(tans33.length-1))
					tansStr33 = tansStr33+tans33[i]+",";
				else
				{
					tansStr33 = tansStr33+tans33[i];
				}
				
			}
		}
		if(tans34!=null)
		{
			for(int i=0; i<tans34.length; i++)
			{
				
				if(i!=(tans34.length-1))
					tansStr34 = tansStr34+tans34[i]+",";
				else
				{
					tansStr34 = tansStr34+tans34[i];
				}
				
			}
		}
		if(tans35!=null)
		{
			for(int i=0; i<tans35.length; i++)
			{
				
				if(i!=(tans35.length-1))
					tansStr35 = tansStr35+tans35[i]+",";
				else
				{
					tansStr35 = tansStr35+tans35[i];
				}
				
			}
		}
			
			
	        	int countA= 0;
	        	int countB= 0;
	        	int countC= 0;
	        	int countD= 0;
	        	int countE= 0;
	        	int countF= 0;
	        	int countG= 0;
	        	int countH= 0;
	        	int countI= 0;
	        	
	        	
	        	 if(tansStr1.equalsIgnoreCase("a")){
	        		countA = countA +1;
	        	}else if(tansStr1.equalsIgnoreCase("b")){
	        		countB = countB +1;
	        	}else if(tansStr1.equalsIgnoreCase("c")){
	        		countC = countC +1;
	        	}else if(tansStr1.equalsIgnoreCase("d")){
	        		countD = countD +1;
	        	}else if(tansStr1.equalsIgnoreCase("e")){
	        		countE = countE +1;
	        	}else if(tansStr1.equalsIgnoreCase("f")){
	        		countF = countF +1;
	        	}else if(tansStr1.equalsIgnoreCase("g")){
	        		countG = countG +1;
	        	}else if(tansStr1.equalsIgnoreCase("h")){
	        		countH = countH +1;
	        	}else if(tansStr1.equalsIgnoreCase("i")){
	        		countI = countI +1;
	        	}else if(tansStr1.equalsIgnoreCase("0")){
	        		
	        	}
	        	
	        	
	        	 if(tansStr2.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr2.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr2.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr2.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr2.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr2.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr2.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr2.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr2.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr2.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr3.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr3.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr3.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr3.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr3.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr3.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr3.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr3.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr3.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr3.equalsIgnoreCase("0")){
		        		
		        	}
		        	
	        	
	        	 if(tansStr4.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr4.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr4.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr4.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr4.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr4.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr4.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr4.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr4.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr4.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr5.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr5.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr5.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr5.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr5.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr5.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr5.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr5.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr5.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr5.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr6.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr6.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr6.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr6.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr6.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr6.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr6.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr6.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr6.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr6.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr7.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr7.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr7.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr7.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr7.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr7.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr7.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr7.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr7.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr7.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr8.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr8.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr8.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr8.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr8.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr8.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr8.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr8.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr8.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr8.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	 if(tansStr9.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr9.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr9.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr9.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr9.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr9.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr9.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr9.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr9.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr9.equalsIgnoreCase("0")){
		        		
		        	}
		        		
		       
	        	
	        	 if(tansStr10.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr10.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr10.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr10.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr10.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr10.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr10.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr10.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr10.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr10.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr11.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr11.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr11.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr11.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr11.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr11.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr11.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr11.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr11.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr11.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	 if(tansStr12.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr12.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr12.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr12.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr12.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr12.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr12.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr12.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr12.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr12.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr13.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr13.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr13.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr13.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr13.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr13.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr13.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr13.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr13.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr13.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr14.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr14.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr14.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr14.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr14.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr14.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr14.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr14.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr14.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr14.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr15.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr15.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr15.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr15.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr15.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr15.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr15.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr15.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr15.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr15.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr16.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr16.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr16.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr16.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr16.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr16.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr16.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr16.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr16.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr16.equalsIgnoreCase("0")){
		        		
		        	}
		        		
		       
	        	 if(tansStr17.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr17.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr17.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr17.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr17.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr17.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr17.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr17.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr17.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr17.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr18.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr18.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr18.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr18.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr18.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr18.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr18.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr18.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr18.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr18.equalsIgnoreCase("0")){
		        		
		        	}
		        		
		       
	        	
	        	 if(tansStr19.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr19.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr19.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr19.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr19.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr19.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr19.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr19.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr19.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr19.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr20.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr20.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr20.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr20.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr20.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr20.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr20.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr20.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr20.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr20.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr21.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr21.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr21.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr21.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr21.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr21.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr21.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr21.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr21.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr21.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr22.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr22.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr22.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr22.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr22.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr22.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr22.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr22.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr22.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr22.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	 if(tansStr23.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr23.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr23.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr23.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr23.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr23.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr23.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr23.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr23.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr23.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr24.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr24.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr24.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr24.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr24.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr24.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr24.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr24.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr24.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr24.equalsIgnoreCase("0")){
		        		
		        	}
		        		
		       
	        	
	        	 if(tansStr25.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr25.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr25.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr25.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr25.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr25.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr25.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr25.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr25.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr25.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr26.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr26.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr26.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr26.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr26.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr26.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr26.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr26.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr26.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr26.equalsIgnoreCase("0")){
		        		
		        	}
		        		
		       
	        	
	        	 if(tansStr27.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr27.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr27.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr27.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr27.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr27.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr27.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr27.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr27.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr27.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	 if(tansStr28.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr28.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr28.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr28.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr28.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr28.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr28.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr28.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr28.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr28.equalsIgnoreCase("0")){
		        		
		        	}
		        		
		       
	        	
	        	 if(tansStr29.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr29.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr29.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr29.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr29.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr29.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr29.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr29.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr29.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr29.equalsIgnoreCase("0")){
		        		
		        	}
		        		
		       
	        	
	        	 if(tansStr30.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr30.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr30.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr30.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr30.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr30.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr30.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr30.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr30.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr30.equalsIgnoreCase("0")){
		        		
		        	}
		        		
		       
	        	
	        	 if(tansStr31.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr31.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr31.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr31.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr31.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr31.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr31.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr31.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr31.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr31.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	 if(tansStr32.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr32.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr32.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr32.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr32.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr32.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr32.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr32.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr32.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr32.equalsIgnoreCase("0")){
		        		
		        	}
	        	
	        	
	        	 if(tansStr33.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr33.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr33.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr33.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr33.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr33.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr33.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr33.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr33.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr33.equalsIgnoreCase("0")){
		        		
		        	}
		        		
		        
	        	
	        	 if(tansStr34.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr34.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr34.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr34.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr34.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr34.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr34.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr34.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr34.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr34.equalsIgnoreCase("0")){
		        		
		        	}
		        		
		       
	        	
	        	 if(tansStr35.equalsIgnoreCase("a")){
		        		countA = countA +1;
		        	}else if(tansStr35.equalsIgnoreCase("b")){
		        		countB = countB +1;
		        	}else if(tansStr35.equalsIgnoreCase("c")){
		        		countC = countC +1;
		        	}else if(tansStr35.equalsIgnoreCase("d")){
		        		countD = countD +1;
		        	}else if(tansStr35.equalsIgnoreCase("e")){
		        		countE = countE +1;
		        	}else if(tansStr35.equalsIgnoreCase("f")){
		        		countF = countF +1;
		        	}else if(tansStr35.equalsIgnoreCase("g")){
		        		countG = countG +1;
		        	}else if(tansStr35.equalsIgnoreCase("h")){
		        		countH = countH +1;
		        	}else if(tansStr35.equalsIgnoreCase("i")){
		        		countI = countI +1;
		        	}else if(tansStr35.equalsIgnoreCase("0")){
		        		
		        	}
	        	/*else if(tans35.equalsIgnoreCase("0")){
	        		ActionErrors errors = new ActionErrors();
	    			errors.add("allQue", new ActionError("errors.student.allQue", "Question 35"));
	    			
	    			if(!errors.isEmpty())
	    			{
	    				saveErrors(request, errors);
	    			}
	    			result = "Pasnaltyfail";
	        	}*/
	        	
	       	        	
	        	
	        	////System.out.println("countA............"+countA);
	        	////System.out.println("countB............"+countB);
	        	////System.out.println("countC............"+countC);
	        	////System.out.println("countD............"+countD);
	        	////System.out.println("countE............"+countE);
	        	////System.out.println("countF............"+countF);
	        	////System.out.println("countG............"+countG);
	        	////System.out.println("countH............"+countH);
	        	////System.out.println("countI............"+countI);
	        	
	        	int testAns[] = {countA,countB,countC,countD,countE,countF,countG,countH,countI};
	        	
	        	//int testSortAns[] = {0,0,0,0,0,0,0,0,0};
	        	
	        	int teamp=0;
	        	int teamp1=0;
	        	int teamp2=0;
	        	
	        	
		       	for(int i=0; i< 9; i++){
		        		for(int j=i; j< 9; j++){


		        			if(teamp<testAns[j]){
		        				
		        				teamp=testAns[j];
		        				teamp1=j;
		        			}
		        			
		        			if(teamp<=testAns[j]){
		        				
		        				teamp=testAns[j];
		        				teamp2=j;
		        			}
			        	}
		        	}
		        	
	        	
		        	
		        int flag1 = 0;
		       
		        
		        String matchType = "";
		        
		        matchType += ""+(teamp1+1)+", ";
		        
		        if(teamp2!=0){
		        	
		        	 matchType += ""+(teamp2+1)+", ";
		        }
		        
		        	matchType = matchType.substring(0, matchType.length()-2);
		        
		        ////System.out.println("matchType............"+matchType);
		        
		        ////////System.out.println("max............"+teamp);
	        	////System.out.println("max..index.teamp1........."+teamp1);
	        	////System.out.println("max..index.teamp2........."+teamp2);	
	        	////////System.out.println("flag1..........."+flag1);	
	        	
		        
		        if(teamp1==teamp2)
		        {
		        	flag1 = 1;
		        	
		        	
		        }else{
		        	
		        	
		        	
		        	ActionErrors errors = new ActionErrors();
	    			errors.add("pasnaltyfail", new ActionError("errors.student.Pasnaltyfail", " "+matchType+""));
	    			
	    			if(!errors.isEmpty())
	    			{
	    				saveErrors(request, errors);
	    			}
	    			
	        	
	    			result = "failure";
	    			return mapping.findForward(result);		        	
		        }
		        
		        if(teamp1==0)
		        {
		        	analysis = "<B>Type One: The Perfectionist, Moralizer, and Reformer</B> -  One is someone who tends to focus on doing things the \"right\" way and is always striving for perfection. Ones have excellent analytical ability and a good eye for details.  Ones are always striving to improve themselves and can see the possibilities for excellence.  Ones avoid anger at all costs, and seek perfection.";
		        }
		        else if(teamp1==1)
		        {
		        	analysis =  "<B>Type Two: The Pleaser, Giver, and Helper</B> - Two is primarily focused on meeting other's needs and often has to learn to say no. Twos are empathic, supportive and make excellent caregivers.  Many Highly Sensitive People (HSPs) <br>are Twos.Twos avoid needing others at all costs, and seek being needed.";
		        }
		        else if(teamp1==2)
		        {
		        	analysis =  "<B>Type Three: The Performer, Organizer, and Achiever</B> - Three tends to focus on doing and on accomplishments and appearances - Threes can get caught up in how things \"look\" image rather than reality.  Threes are often highly self-assured and competitive, and make natural authority figures.  Threes avoid failure at all costs, and seek prestige.";
		        }
		        else if(teamp1==3)
		        {
		        	analysis =  "<B>Type Four: The Dreamer, Individualist, Romantic, Tragic Romantic </B>- Fours are always aware of what is missing, and are often longing for what they don't have.  At the same time, Fours are often highly creative and unique, and make excellent problem-solvers since they can always see how to make things better. Fours focus most on connection and feeling. Many HSPs are Fours. Fours avoid the ordinary at all costs, and seek uniqueness & originality";
		        }
		        else if(teamp1==4)
		        {
		        	analysis =  "<B>Type Five: The Thinker, Observer, and Investigator</B> - Fives tend to hang out in the background and watch what's going on.  They are the thinkers of the group.  Fives are rational, calm and objective.  Fives avoid greed at all costs, and seek knowledge and intellectual understanding. Many HSP’s are Fives.  What would be the type of our Prime Minister?";
		        }
		        else if(teamp1==5)
		        {
		        	analysis =  "<B>Type Six: The Risk Assessor, Loyalist, and Devil's Advocate, Questioner</B> - Sixes have a strong focus on the potential for danger or unsafe circumstances and therefore always liked to be prepared.  There are actually two kinds of Sixes - phobic and counter-phobic.  Most Sixes tend to have some kind of conflict or struggle with authority issues.  Sixes are also highly loyal, responsible and protective. Sixes avoid feeling vulnerable or unsafe at all costs, and seek security.";
		        }
		        else if(teamp1==6)
		        {
		        	analysis =  "<B>Type Seven: The Enthusiast, Epicure, and Entertainer</B> - Sevens are youthful, optimistic and idealistic and tend to focus most on playtime. They often have problems with making commitments and tend to escape their own lives by retreating into fantasy.  Sevens are visionaries and entertainers. Sevens avoid pain at all costs, and seek ease, play and fun";
		        }
		        else if(teamp1==7)
		        {
		        	analysis =  "<B>Type Eight: The Challenger, Boss, and Protector</B> - Eights are very protective - a safe harbor - and yet can be confrontational when the situation demands it.  Eights are natural leaders (along with threes) and have the ability to \"take charge\" of a situation.  They utilize their anger as a source of power in their lives. Eights avoid weakness at all costs, and seek strength and power";
		        }
		        else if(teamp1==8)
		        {
		        	analysis =  "<B>Type Nine: The Peacekeeper, Mediator </B> - Nines tend to forget themselves and allow themselves to succumb to the agendas of their loved ones.  Nines have a tendency to \"go to sleep\" to their own lives and might have trouble prioritizing. Nines are brilliant \"peacekeepers\" because they have learned to minimize conflict. Nines love unconditionally and are excellent listeners. Nines avoid conflict at all costs, and seek tranquility, peace and harmony (both inner and outer).";
		        }
		        
		        
	        	////////System.out.println("analysis............"+analysis); 
	        	
	        	java.util.Date dt = new java.util.Date();
				SimpleDateFormat sform = new SimpleDateFormat("yyyy-MM-dd, HH:mm:ss,a");
				String completeRemDate = sform.format(dt);
				StringTokenizer sttotal = new StringTokenizer(completeRemDate, ",");
			    String creationDate = sttotal.nextToken();
			    
	        	datavec.add(String.valueOf(testId));
		        datavec.add(uId);		     
		        datavec.add("N/A");
		        datavec.add("N/A");
		        datavec.add(analysis); 
		        datavec.add(testName);
		        datavec.add(creationDate);
		        datavec.add("0");
		        
		        //System.out.println("resultVec1...Size........."+datavec);
		        
		        Vector <String> datavec2 = new Vector<String>();	
				datavec2.add(String.valueOf("0"));	
	            datavec2.add(String.valueOf("20"));	
		        datavec2.add(uId);	
		        
		        
		        Vector resultVec1 = indvMaster.getTestVecList(ds, datavec2);
		        ////////System.out.println("resultVec1...Size........."+resultVec1.size());
	        	
		        int flag2 = 0;
		        ////////System.out.println("flag2.........."+flag2);
		        
		        
				        if(resultVec1.size()!=0){
						        for(int i=0; i<resultVec1.size(); i++)
								{
									int j = i+1;
									 Vector teampVec = (Vector)resultVec1.elementAt(i);
									 String teampTestId = teampVec.elementAt(0).toString().trim();
									 if(teampTestId.equalsIgnoreCase(testId1))
									 {
										 flag2 = 1;
									 }
								}
				        }
				        if (flag2==1){
				        	
				        					        	
			    			ActionErrors errors = new ActionErrors();
			    			errors.add("testDuplicat", new ActionError("errors.student.testDuplicat"));
			    			
			    			if(!errors.isEmpty())
			    			{
			    				saveErrors(request, errors);
			    			}
			    			
			        	
			        	result = "failure";
			        	return mapping.findForward(result);
			        }
		      
		       
		        if((flag1==1)&&(flag2==0)){
		        	
		        		////////System.out.println("In side for loop.........");
		        	  result = indvMaster.setTestVec(ds, datavec);
		        	
		        }
		        
		        if(result.equalsIgnoreCase("success")){
		        	
		        	ActionErrors errors = new ActionErrors();
	    			errors.add("testsuccess", new ActionError("success.student.testsuccess"));
	    			
	    			if(!errors.isEmpty())
	    			{
	    				saveErrors(request, errors);
	    			}
		        }
		       
		        
	        }
	        
			////System.out.println("result...#########33333333........."+result);
					
			return mapping.findForward(result);
			
		}
}