/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.student.action;

import java.io.PrintWriter;
import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
//import javax.sql.DataSource;
import com.mm.core.master.RootMaster;

/** 
 * MyEclipse Struts
 * Creation date: 06-30-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ShortProAction extends Action {
	RootMaster rootMaster= new RootMaster();
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception {
			HttpSession session =request.getSession();
			int numPId = (request.getParameter("compid")!=null) ? Integer.parseInt(request.getParameter("compid").trim()) : 0;
			String pType = (request.getParameter("pType")!=null) ? request.getParameter("pType").trim() : " ";
			String mcat = (request.getParameter("mcat")!=null) ? request.getParameter("mcat").trim() : " ";
			
			
			//System.out.println("request.getParameter()>>>>>>>>in short pro action>>>>>>>>>"+request.getParameter("pType"));
			String strResult =" ";
			if(pType.equalsIgnoreCase("comp"))
			{
				String profile = rootMaster.getCompanyshortpro( getDataSource(request, "student"),numPId);
				//System.out.println("profile>>>>>>>>in short pro action>>>>>>>>>"+profile.length());
				//System.out.println("profile>>>>>>>>in short pro action>>>>>>>>>"+profile);
				if(numPId!=0)
					{
					strResult ="<table width=\"100%\" ><tr bgcolor=\"#A5CEBE\"><td align=\"center\" class=\"bold\"> Company Short Profile</td></tr><tr><td valign=\"top\" bgcolor=\"#f6f3f3\">";
					
					if(profile.length()>0)
					{
						strResult += "	<div align=\"justify\" >"+profile+"</div><input type=\"hidden\" id=\"hide\" name=\"hide\" value=\"0\"></td>";
						
					}else
					{
						strResult += "	<div align=\"center\" ><img  src=\"../images/noprofile.jpg\" width=\"100%\" height=\"100%\"></img></div><input type=\"hidden\" id=\"hide\" name=\"hide\" value=\"0\"></td>";
					}
					strResult += "</tr></table>";
					}
			}else
			{ 	int uid=Integer.parseInt((String)session.getAttribute("uId"));
				String userid="failure";
				char c=mcat.charAt(0);
				if(Character.isDigit(c))
				{
				userid=rootMaster.getResult(getDataSource(request, "student"), uid, numPId);
				}
				String profile = rootMaster.getUsershortpro( getDataSource(request, "student"),numPId);
				
				if(numPId!=0)
					{
					strResult ="<table width=\"100%\" ><tr bgcolor=\"#A5CEBE\"><td align=\"center\" class=\"bold\"> Contact Person Short Profile</td></tr>";
					if(!userid.equalsIgnoreCase("failure")){
					if(numPId==Integer.parseInt(userid))
					{
						strResult +="<tr><td valign=\"top\" bgcolor=\"#f6f3f3\">";
						strResult +="<input type=\"hidden\" id=\"hide\" name=\"hide\" value=\"1\">";
						strResult += "	<div align=\"justify\" ><font color=\"red\" >Your Previous Request is already Rejected by this person .<br>so you are not able to send request again.</div>";
						strResult +="</tr></tr>";
						
					}
					}
					strResult +="<tr><td valign=\"top\" bgcolor=\"#f6f3f3\">";
					
					if(profile.length()>0)
					{
						strResult += "	<div align=\"justify\" >"+profile+"</div><input type=\"hidden\" id=\"hide\" name=\"hide\" value=\"0\"></td>";
						
					}else
					{
						strResult += "	<div align=\"center\" ><img  src=\"../images/noprofile.jpg\" width=\"100%\" height=\"100%\"></img></div><input type=\"hidden\" id=\"hide\" name=\"hide\" value=\"0\"></td>";
					}
					strResult += "</tr></table>";
					}
			}
			
			response.setContentType("text/html;charset=ISO-8859-1");
		    PrintWriter out = response.getWriter();
		    out.println(strResult);
		    out.flush();
			return null;
	}
	
	
	
	
}