

/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */

package com.mm.struts.entp.form;

import org.apache.struts.validator.ValidatorForm;


/** 
 * MyEclipse Struts
 * Creation date: 06-20-2007
 * 
 * XDoclet definition:
 * @struts.form name="MailComplaintsForm"
 */
public class MailComplaintsForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** text property */
	private String grpNamesTxtFld = "";
	private String subject = "";
	private String box = "";
	private String recpName = "";
	private String fcopmId = "";
	private String tagId = "";
	
	/** 
	 * Returns the grpNamesTxtFld.
	 * @return String
	 */
	public String getTagId() {
		return tagId;
	}

	/** 
	 * Set the grpNamesTxtFld.
	 * @param grpNamesTxtFld The grpNamesTxtFld to set
	 */
	public void setTagId(String tagId) {
		this.tagId = tagId;
	}
	
	/** 
	 * Returns the grpNamesTxtFld.
	 * @return String
	 */
	public String getFcopmId() {
		return fcopmId;
	}

	/** 
	 * Set the grpNamesTxtFld.
	 * @param grpNamesTxtFld The grpNamesTxtFld to set
	 */
	public void setFcopmId(String fcopmId) {
		this.fcopmId = fcopmId;
	}
	
	/** 
	 * Returns the grpNamesTxtFld.
	 * @return String
	 */
	public String getRecpName() {
		return recpName;
	}

	/** 
	 * Set the grpNamesTxtFld.
	 * @param grpNamesTxtFld The grpNamesTxtFld to set
	 */
	public void setRecpName(String recpName) {
		this.recpName = recpName;
	}
	
	/** 
	 * Returns the grpNamesTxtFld.
	 * @return String
	 */
	public String getGrpNamesTxtFld() {
		return grpNamesTxtFld;
	}

	/** 
	 * Set the grpNamesTxtFld.
	 * @param grpNamesTxtFld The grpNamesTxtFld to set
	 */
	public void setGrpNamesTxtFld(String grpNamesTxtFld) {
		this.grpNamesTxtFld = grpNamesTxtFld;
	}
	/** 
	 * Returns the subject.
	 * @return String
	 */
	public String getSubject() {
		return subject;
	}

	/** 
	 * Set the subject.
	 * @param subject The subject to set
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/** 
	 * Returns the box.
	 * @return String
	 */
	public String getBox() {
		return box;
	}

	/** 
	 * Set the box.
	 * @param box The box to set
	 */
	public void setBox(String box) {
		this.box = box;
	}
	
	
}