package com.mm.struts.form;
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */



import org.apache.struts.validator.ValidatorForm;

public class AddFacilityForm  extends ValidatorForm {
	/*
	 * Generated fields
	 */

	private String builder= "";
	private String address= "";
	private String facilityName= "";
	private String collegeCountry= "";
	private String collegeState= "";
	private String collegeCity= "";
	private String zipcode= "";


	/*
	 * Generated Methods
	 */
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getBuilder() {
		return builder;
	}
	public void setBuilder(String builder) {
		this.builder = builder;
	}
	public String getCollegeCity() {
		return collegeCity;
	}
	public void setCollegeCity(String collegeCity) {
		this.collegeCity = collegeCity;
	}
	public String getCollegeCountry() {
		return collegeCountry;
	}
	public void setCollegeCountry(String collegeCountry) {
		this.collegeCountry = collegeCountry;
	}
	public String getCollegeState() {
		return collegeState;
	}
	public void setCollegeState(String collegeState) {
		this.collegeState = collegeState;
	}
	public String getFacilityName() {
		return facilityName;
	}
	public void setFacilityName(String facilityName) {
		this.facilityName = facilityName;
	}
	public String getZipcode() {
		return zipcode;
	}
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}


//System.out.println("In FORRRM   80:");	
}
