	/*
	 * Generated by MyEclipse Struts
	 * Template path: templates/java/JavaClass.vtl
	 */
	package com.mm.struts.form;

	import org.apache.struts.validator.ValidatorForm;

	/** 
	 * MyEclipse Struts
	 * Creation date: 06-06-2007
	 * 
	 * XDoclet definition:
	 * @struts.form name="loginForm"
	 */
	public class ComplaintsresponseForm extends ValidatorForm {
		/*
		 * Generated fields
		 */

		/**
		 * 
		 */
		private static final long serialVersionUID = 1L;

		/** loginId property */
		private String fcomplainId = "";
		private String complainTitle = "";
		private String responses = "";
		/** 
		 * Returns the fcom_id.
		 * @return String
		 */
		public String getFcomplainId() {
			return this.fcomplainId;
		}

		/** 
		 * Set the fcomplainId.
		 * @param fcomplainId The fcomplainId to set
		 */
		public void setFcomplainId(String fcomplainId) {
			this.fcomplainId = fcomplainId;
		}

		/** 
		 * Returns the complainTitle.
		 * @return String
		 */
		public String getComplainTitle() {
			return this.complainTitle;
		}

		/** 
		 * Set the complainTitle.
		 * @param complainTitle The complainTitle to set
		 */
		public void setComplainTitle(String complainTitle) {
			this.complainTitle = complainTitle;
		}
		/** 
		 * Returns the cmbCategory.
		 * @return String
		 */
		public String getResponses() {
			return this.responses;
		}

		/** 
		 * Set the responses.
		 * @param responses The responses to set
		 */
		public void setResponses(String responses) {
			this.responses = responses;
		}	
		
		
	}
