/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.form;

import org.apache.struts.validator.ValidatorForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionError;
import javax.servlet.http.*;

/** 
 * MyEclipse Struts
 * Creation date: 06-27-2007
 * 
 * XDoclet definition:
 * @struts.form name="firstCreationForm"
 */
public class FirstCreationForm extends ValidatorForm {

	/**
	 * 
	 */
	
	
	/**
	 * otherCollegeName
	 */
	
	private static final long serialVersionUID = 1L;
	/** companyCity property */	
	
	/**  status */
	private String status;
	public String getStatus() {
		return status;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}
	
	
	/**  otherCollegeName */
	private String otherCollegeName;
	
	/** 
	 * Returns the otherCollegeName.
	 * @return String
	 */
	public String getOtherCollegeName() {
		return otherCollegeName;
	}
	/** 
	 * Set the otherCollegeName.
	 * @param otherCollegeName The otherCollegeName to set
	 */
	public void setOtherCollegeName(String otherCollegeName) {
		this.otherCollegeName = otherCollegeName;
	}
	
	/** password txtCollege_id */
	private String txtCollege_id;
	
	/** 
	 * Returns the txtCollege_id.
	 * @return String
	 */
	public String getTxtCollege_id() {
		return txtCollege_id;
	}
	/** 
	 * Set the txtCollege_id.
	 * @param txtCollege_id The txtCollege_id to set
	 */
	public void setTxtCollege_id(String txtCollege_id) {
		this.txtCollege_id = txtCollege_id;
	}
	
	/** password txtCourse */
	private String txtCourse;
	
	/** 
	 * Returns the txtCourse.
	 * @return String
	 */
	public String getTxtCourse() {
		return txtCourse;
	}
	/** 
	 * Set the txtCourse.
	 * @param txtCourse The txtCourse to set
	 */
	public void setTxtCourse(String txtCourse) {
		this.txtCourse = txtCourse;
	}
	
	/** password txtOthCourse */
	private String txtOthCourse;
	
	/** 
	 * Returns the txtOthCourse.
	 * @return String
	 */
	public String getTxtOthCourse() {
		return txtOthCourse;
	}
	/** 
	 * Set the txtOthCourse.
	 * @param txtOthCourse The txtOthCourse to set
	 */
	public void setTxtOthCourse(String txtOthCourse) {
		this.txtOthCourse = txtOthCourse;
	}
	
	/** password txtSubject */
	private String txtSubject;
	
	/** 
	 * Returns the txtSubject.
	 * @return String
	 */
	public String getTxtSubject() {
		return txtSubject;
	}
	/** 
	 * Set the txtSubject.
	 * @param txtSubject The txtSubject to set
	 */
	public void setTxtSubject(String txtSubject) {
		this.txtSubject = txtSubject;
	}
	
	/** password txtOthSubject */
	private String txtOthSubject;
	
	/** 
	 * Returns the txtOthSubject.
	 * @return String
	 */
	public String getTxtOthSubject() {
		return txtOthSubject;
	}
	/** 
	 * Set the txtOthSubject.
	 * @param txtOthSubject The txtOthSubject to set
	 */
	public void setTxtOthSubject(String txtOthSubject) {
		this.txtOthSubject = txtOthSubject;
	}
	
	/** password txtAdmission_no */
	private String txtAdmission_no;
	
	/** 
	 * Returns the txtAdmission_no.
	 * @return String
	 */
	public String getTxtAdmission_no() {
		return txtAdmission_no;
	}
	/** 
	 * Set the txtAdmission_no.
	 * @param txtAdmission_no The txtAdmission_no to set
	 */
	public void setTxtAdmission_no(String txtAdmission_no) {
		this.txtAdmission_no = txtAdmission_no;
	}
	
	/** password cons_cate */
	private String cons_cate;
	
	/** 
	 * Returns the cons_cate.
	 * @return String
	 */
	public String getCons_cate() {
		return cons_cate;
	}
	/** 
	 * Set the cons_cate.
	 * @param cons_cate The cons_cate to set
	 */
	public void setCons_cate(String cons_cate) {
		this.cons_cate = cons_cate;
	}
	
	
	
	/** password property */
	private String loginType;
	
	/** 
	 * Returns the loginType.
	 * @return String
	 */
	public String getLoginType() {
		return loginType;
	}
	/** 
	 * Set the loginType.
	 * @param loginType The loginType to set
	 */
	public void setLoginType(String loginType) {
		this.loginType = loginType;
	}
	
	private String othercompanyCity="";
	
	/** companyState property */	
	private String othercompanyState="";
	
	/** compCountry property */	
	private String othercompCountry="";
	
	/** community property */	
	private String community="";
	
	
	/** userID property */
	private String userID = "";
	
	/** 
	 * Returns the userID.
	 * @return String
	 */
	public String getUserID() {
		return userID;
	}
	/** 
	 * Set the userID.
	 * @param userID The userID to set
	 */
	public void setUserID(String userID) {
		this.userID = userID;
	}
	
	
	/** userPassword property */
	private String userPassword = "";
	/** 
	 * Returns the userPassword.
	 * @return String
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/** 
	 * Set the userPassword.
	 * @param userPassword The userPassword to set
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}
	
	
	/** userRePassword property */
	private String userRePassword = "";
	/** 
	 * Returns the userRePassword.
	 * @return String
	 */
	public String getUserRePassword() {
		return userRePassword;
	}

	/** 
	 * Set the userRePassword.
	 * @param userRePassword The userRePassword to set
	 */
	public void setUserRePassword(String userRePassword) {
		this.userRePassword = userRePassword;
	}
	
	
	/** userFirstName property */
	private String userFirstName = "";
	/** 
	 * Returns the userFirstName.
	 * @return String
	 */
	public String getUserFirstName() {
		return this.userFirstName;
	}
	/** 
	 * Set the userFirstName.
	 * @param userFirstName The userFirstName to set
	 */
	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	/** userLastName property */
	private String userLastName = "";
	/** 
	 * Returns the userLastName.
	 * @return String
	 */
	public String getUserLastName() {
		return this.userLastName ;
	}
	/** 
	 * Set the userLastName.
	 * @param userLastName The userLastName to set
	 */
	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}
	
	
	/** cmbGender property */
	private String cmbGender = "";
	/** 
	 * Returns the cmbGender.
	 * @return String
	 */
	public String getCmbGender() {
		return this.cmbGender;
	}	
	/** 
	 * Set the cmbGender.
	 * @param cmbGender The cmbGender to set
	 */
	public void setCmbGender(String cmbGender) {
		this.cmbGender = cmbGender;
	}
	
	
	/** cmbDate property */
	private String cmbDate = "";
	
	/** 
	 * Returns the cmbDate.
	 * @return String
	 */
	public String getCmbDate() {
		return this.cmbDate;
	}
	/** 
	 * Set the cmbDate.
	 * @param cmbDate The cmbDate to set
	 */
	public void setCmbDate(String cmbDate) {
		this.cmbDate = cmbDate;
	}
	
	
	/** cmbMonth property */
	private String cmbMonth = "";
	/** 
	 * Returns the cmbMonth.
	 * @return String
	 */
	public String getCmbMonth() {
		return this.cmbMonth;
	}

	/** 
	 * Set the cmbMonth.
	 * @param cmbMonth The cmbMonth to set
	 */
	public void setCmbMonth(String cmbMonth) {
		this.cmbMonth = cmbMonth;
	}
	
	
	/** cmbYear property */
	private String cmbYear = "";
	/** 
	 * Returns the cmbYear.
	 * @return String
	 */
	public String getCmbYear() {
		return this.cmbYear;
	}
	/** 
	 * Set the cmbYear.
	 * @param cmbYear The cmbYear to set
	 */
	public void setCmbYear(String cmbYear) {
		this.cmbYear = cmbYear;
	}
	
	
	/** maritalCombo property */
	private String maritalCombo = "NA";	
	/** 
	 * Returns the maritalCombo.
	 * @return String
	 */
	public String getMaritalCombo() {
		return this.maritalCombo;
	}
	/** 
	 * Set the maritalCombo.
	 * @param maritalCombo The maritalCombo to set
	 */
	public void setMaritalCombo(String maritalCombo) {
		this.maritalCombo = maritalCombo;
	}
	
	/** txtAddress property */
	private String txtAddress = "";
	/** 
	 * Returns the txtAddress.
	 * @return String
	 */
	public String getTxtAddress() {
		return this.txtAddress;
	}
	/** 
	 * Set the txtAddress.
	 * @param txtAddress The txtAddress to set
	 */
	public void setTxtAddress(String txtAddress) {
		this.txtAddress = txtAddress;
	}
	
	/** userCity property */
	private String companyCity = "";
	/** 
	 * Returns the userCity.
	 * @return String
	 */
	public String getCompanyCity() {
		return this.companyCity;
	}

	/** 
	 * Set the companyCity.
	 * @param companyCity The companyCity to set
	 */
	public void setCompanyCity(String companyCity) {
		this.companyCity = companyCity;
	}
	
	/** userState property */
	private String companyState = "";
	/** 
	 * Returns the userState.
	 * @return String
	 */
	public String getCompanyState() {
		return this.companyState;
	}

	/** 
	 * Set the companyState.
	 * @param companyState The companyState to set
	 */
	public void setCompanyState(String companyState) {
		this.companyState = companyState;
	}
	
	
	/** userCountry property */
	private String compCountry = "";
	/** 
	 * Returns the userCountry.
	 * @return String
	 */
	public String getCompCountry() {
		return this.compCountry;
	}

	/** 
	 * Set the compCountry.
	 * @param cCountry The compCountry to set
	 */
	public void setCompCountry(String compCountry) {
		this.compCountry = compCountry;
	}
	public String getOthercompanyCity() {
		return this.othercompanyCity;
	}

	/** 
	 * Set the companyCity.
	 * @param companyCity The companyCity to set
	 */
	public void setOthercompanyCity(String othercompanyCity) {
		this.othercompanyCity = othercompanyCity;
	}
	
	
	
	private String builderFacility = "";
	/** 
	 * Returns the service id
	 * @return String
	 */
	public String getbuilderFacility() {
		return this.builderFacility;
	}
	/** 
	 * Set the userFirstName.
	 * @param userFirstName The userFirstName to set
	 */
	public void setbuilderFacility(String builderFacility) {
		this.builderFacility = builderFacility;
	}
	
	private String builder = "";
	/** 
	 * Returns the towerName.
	 * @return String
	 */
	public String getbuilder() {
		return this.builder;
	}
	/** 
	 * Set the userFirstName.
	 * @param userFirstName The userFirstName to set
	 */
	public void setbuilder(String builder) {
		this.builder = builder;
	}


	
	private String builderDesignation = "";
	/** 
	 * Returns the designation
	 * @return String
	 */
	public String getbuilderDesignation() {
		return this.builderDesignation;
	}
	/** 
	 * Set the userFirstName.
	 * @param userFirstName The userFirstName to set
	 */
	public void setbuilderDesignation(String designation) {
		this.builderDesignation = builderDesignation;
	}

	private String builderCity = "";
	/** 
	 * Returns the towerName.
	 * @return String
	 */
	public String getbuilderCity() {
		return this.builderCity;
	}
	/** 
	 * Set the userFirstName.
	 * @param userFirstName The userFirstName to set
	 */
	public void setbuilderCity(String builderCity) {
		this.builderCity = builderCity;
	}

	
	/** 
	 * Returns the companyState.
	 * @return String
	 */
	public String getOthercompanyState() {
		return this.othercompanyState;
	}

	/** 
	 * Set the companyState.
	 * @param companyState The companyState to set
	 */
	public void setOthercompanyState(String othercompanyState) {
		this.othercompanyState = othercompanyState;
	}
	
	
	/** 
	 * Returns the compCountry.
	 * @return String
	 */
	public String getOthercompCountry() {
		return this.othercompCountry;
	}

	/** 
	 * Set the compCountry.
	 * @param cCountry The compCountry to set
	 */
	public void setOthercompCountry(String othercompCountry) {
		this.othercompCountry = othercompCountry;
	}
	/**community*/
	public String getCommunity() {
		return this.community;
	}

	/** 
	 * Set the txtPincode.
	 * @param txtPincode The txtPincode to set
	 */
	public void setCommunity(String community) {
		this.community = community;
	}
	/** txtPincode property */
	
	private String txtPincode = "";
	/** 
	 * Returns the txtPincode.
	 * @return String
	 */
	public String getTxtPincode() {
		return this.txtPincode;
	}

	/** 
	 * Set the txtPincode.
	 * @param txtPincode The txtPincode to set
	 */
	public void setTxtPincode(String txtPincode) {
		this.txtPincode = txtPincode;
	}
	
	/** txtPrefix property */
	private String txtPrefix = "+91";
	/** 
	 * Returns the txtPrefix.
	 * @return String
	 */
	public String getTxtPrefix() {
		return this.txtPrefix;
	}
	/** 
	 * Set the txtPrefix.
	 * @param txtPrefix The txtPrefix to set
	 */
	public void setTxtPrefix(String txtPrefix) {
		this.txtPrefix = txtPrefix;
	}
	
	/** txtMobile property */
	private String txtMobile = "";
	/** 
	 * Returns the txtMobile.
	 * @return String
	 */
	public String getTxtMobile() {
		return this.txtMobile;
	}
	/** 
	 * Set the txtMobile.
	 * @param txtMobile The txtMobile to set
	 */
	public void setTxtMobile(String txtMobile) {
		this.txtMobile = txtMobile;
	}
	
	
	/** txtPrefix property */
	private String landPrefix = "011";
	/** 
	 * Returns the landPrefix.
	 * @return String
	 */
	public String getlandPrefix() {
		return this.landPrefix;
	}
	/** 
	 * Set the landline prefix.
	 * 
	 */
	public void setlandPrefix(String landPrefix) {
		this.landPrefix = landPrefix;
	}
	
	/** landLine property */
	private String landLine = "";
	/** 
	 * Returns the txtMobile.
	 * @return String
	 */
	public String getlandLine() {
		return this.landLine;
	}
	/** 
	 * Set the landline.
	 * @param landLine The landLine to set
	 */
	public void setlandLine(String landLine) {
		this.landLine = landLine;
	}
	
	
	/** userEMail property */
	private String userEMail = "";
	/** 
	 * Returns the userEMail.
	 * @return String
	 */
	public String getUserEMail() {
		return this.userEMail;
	}
	/** 
	 * Set the userEMail.
	 * @param userEMail The userEMail to set
	 */
	public void setUserEMail(String userEMail) {
		this.userEMail = userEMail;
	}
	
	/** educationCombo property */
	private String educationCombo = "";
	/** 
	 * Returns the educationCombo.
	 * @return String
	 */
	public String getEducationCombo() {
		return this.educationCombo;
	}
	/** 
	 * Set the educationCombo.
	 * @param educationCombo The educationCombo to set
	 */
	public void setEducationCombo(String educationCombo) {
		this.educationCombo = educationCombo;
	}	
	/** professionCombo property */
	private String professionCombo = "";
	/** 
	 * Returns the professionCombo.
	 * @return String
	 */
	public String getProfessionCombo() {
		return this.professionCombo;
	}
	/** 
	 * Set the professionCombo.
	 * @param professionCombo The professionCombo to set
	 */
	public void setProfessionCombo(String professionCombo) {
		this.professionCombo = professionCombo;
	}
	
	/** educationCombo property */
	private String annualincomeCombo = "";
	/** 
	 * Returns the annualincomeCombo.
	 * @return String
	 */
	public String getAnnualincomeCombo() {
		return this.annualincomeCombo;
	}
	/** 
	 * Set the annualincomeCombo.
	 * @param annualincomeCombo The annualincomeCombo to set
	 */
	public void setAnnualincomeCombo(String annualincomeCombo) {
		this.annualincomeCombo = annualincomeCombo;
	}
	
	/** aboutUsCombo property */
	private String aboutUsCombo = "";	
	/** 
	 * Returns the aboutUsCombo.
	 * @return String
	 */
	public String getAboutUsCombo() {
		return this.aboutUsCombo;
	}
	/** 
	 * Set the aboutUsCombo.
	 * @param aboutUsCombo The aboutUsCombo to set
	 */
	public void setAboutUsCombo(String aboutUsCombo) {
		this.aboutUsCombo = aboutUsCombo;
	}
	
	/** agreement property */
	private String agreement = "";
	/** 
	 * Returns the agreement.
	 * @return String
	 */
	public String getAgreement() {
		return this.agreement;
	}
	/** 
	 * Set the agreement.
	 * @param agreement The agreement to set
	 */
	public void setAgreement(String agreement) {
		this.agreement = agreement;
	}
	
	/**  collegeCountry */
	private String collegeCountry;
	
	/** 
	 * Returns the collegeCountry.
	 * @return String
	 */
	public String getCollegeCountry() {
		return "90~94";
	}
	/** 
	 * Set the collegeCountry.
	 * @param collegeCountry The collegeCountry to set
	 */
	public void setCollegeCountry(String collegeCountry) {
		this.collegeCountry = collegeCountry;
	}
	
	/**  collegeState */
	private String collegeState;
	
	/** 
	 * Returns the collegeState.
	 * @return String
	 */
	public String getCollegeState() {
		return collegeState;
	}
	/** 
	 * Set the collegeState.
	 * @param collegeState The collegeState to set
	 */
	public void setCollegeState(String collegeState) {
		this.collegeState = collegeState;
	}
	
	/**  collegeCity */
	private String collegeCity;
	
	/** 
	 * Returns the collegeCity.
	 * @return String
	 */
	public String getCollegeCity() {
		return collegeCity;
	}
	
	
	private String otherCollegeCity="";
	
	/** companyState property */	
	private String otherCollegeState="";
	
	/** compCountry property */	
	private String otherCollegeCountry="";
	
	
	public String getOtherCollegeCountry() {
		return this.otherCollegeCountry;
	}
	
	public void setOtherCollegeCountry(String otherCollegeCountry) {
		this.otherCollegeCountry = otherCollegeCountry;
	}
	
	public String getOtherCollegeState() {
		return this.otherCollegeState;
	}
	
	public void setOtherCollegeState(String otherCollegeState) {
		this.otherCollegeState = otherCollegeState;
	}
	
	public String getOtherCollegeCity() {
		return this.otherCollegeCity;
	}
	
	public void setOtherCollegeCity(String otherCollegeCity) {
		this.otherCollegeCity = otherCollegeCity;
	}
	
	
	/** 
	 * Set the collegeCity.
	 * @param collegeCity The collegeCity to set
	 */
	public void setCollegeCity(String collegeCity) {
		this.collegeCity = collegeCity;
	}
	//validatin for the user creatin form. it chaek password and retype password will be same.
	//and also check for the country ,state ,city others field 
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest req)
	{	
		String cid = this.compCountry;
		req.setAttribute("cid", cid);
		
		if(cid.equalsIgnoreCase("-1~+0"))
		{
			String othercompCountry = this.othercompCountry;
			req.setAttribute("othercompCountry", othercompCountry);
			////System.out.println("othercompCountry....FirstCreationForm......"+othercompCountry);
		}
		
		String sid = this.companyState;
		req.setAttribute("sid", sid);
		if(sid.equalsIgnoreCase("-1"))
		{
			String othercompanyState = this.othercompanyState;
			req.setAttribute("othercompanyState", othercompanyState);
			////System.out.println("othercompanyState....FirstCreationForm......"+othercompanyState);
		}
			
		String pid = this.companyCity;
		req.setAttribute("pid", pid);
		////System.out.println("pid....FirstCreationForm......"+pid);
		if(pid.equalsIgnoreCase("-1"))
		{
			String othercompanyCity = this.othercompanyCity;
			req.setAttribute("othercompanyCity", othercompanyCity);
			////System.out.println("othercompanyCity....FirstCreationForm......"+othercompanyCity);
		}
		
		
		
		String cid2 = "-1~+0";
		//this.collegeCountry;
		req.setAttribute("cid2", cid2);
		System.out.println("cid2....FirstCreationForm...Ajay..."+cid2);
		if(cid2.equalsIgnoreCase("-1~+0"))
		{
			String othercompCountry2 = this.otherCollegeCountry;
			req.setAttribute("othercompCountry2", othercompCountry2);
			////System.out.println("othercompCountry2....FirstCreationForm......"+othercompCountry2);
		}
		
		String sid2 = this.collegeState;
		req.setAttribute("sid2", sid2);
		System.out.println("sid2....FirstCreationForm......"+sid2);
		req.setAttribute("othercompanyState2","0");
		String pid2 = "-1";
		req.setAttribute("pid2", "pid2");
		System.out.println("pid2....FirstCreationForm......"+pid2);
		if(pid2.equalsIgnoreCase("-1"))
		{
			String othercompanyCity2 = "otherCollegeCity";
			req.setAttribute("othercompanyCity2", othercompanyCity2);
			////System.out.println("othercompanyCity2....FirstCreationForm......"+othercompanyCity2);
		}
		
		
		String college = "JIIT Noida";
		req.setAttribute("college", college);
		System.out.println("24aug....FirstCreationForm......"+college);
		if(college.equalsIgnoreCase("-1"))
		{
			String othercollege = this.otherCollegeName;
			req.setAttribute("othercollege", othercollege);
			////System.out.println("othercollege....FirstCreationForm......"+othercollege);
		}
		
		
		String course = "MCA";
		req.setAttribute("course", course);
		System.out.println("course....FirstCreationForm......"+course);
		if(course.equalsIgnoreCase("-1"))
		{
			String othercourse = this.txtOthCourse;
			req.setAttribute("othercourse", othercourse);
			System.out.println("othercourse....FirstCreationForm......"+othercourse);
		}
		
		String stream = "Computers";
		req.setAttribute("stream", stream);
		System.out.println("stream....FirstCreationForm......"+stream);
		if(stream.equalsIgnoreCase("-1"))
		{
			String otherstream = this.txtOthSubject;
			req.setAttribute("otherstream", otherstream);
			System.out.println("otherstream....FirstCreationForm......"+otherstream);
		}
		
		
		
		
		String commuId = this.community;
		req.setAttribute("commuId", commuId);
		
		ActionErrors errors = super.validate(mapping,req);
		if(!(this.userPassword.equals(this.userRePassword)))
		{
			errors.add("FirstCreationForm",new ActionError("errors.resource.match","password" , "retype password"));
		}
		
		
		if(this.txtPrefix.equals("-1"))
		{
			errors.add("FirstCreationForm",new ActionError("errors.resource.valid","mobile prefix"));
		}
		

		if(this.landPrefix.equals("-1"))
		{
			errors.add("FirstCreationForm",new ActionError("errors.resource.valid","LandLine prefix"));
		}
		return errors;
	}
	
	//end of validatin methd  this.community
	
}