	/*
	 * Generated by MyEclipse Struts
	 * Template path: templates/java/JavaClass.vtl
	 */
	package com.mm.struts.form;

	import org.apache.struts.validator.ValidatorForm;

	/** 
	 * MyEclipse Struts
	 * Creation date: 06-06-2007
	 * 
	 * XDoclet definition:
	 * @struts.form name="loginForm"
	 */
	public class SendMailForm extends ValidatorForm {
		/*
		 * Generated fields
		 */

		/**
		 * 
		 */
		private static final long serialVersionUID = 1L;

		
		
		
		
		private String rname = "";
		private String remail = "";
		private String sname = "";
		private String semail = "";
		private String subject = "";
		private String message = "";
		
		private String copy = "";
		/** 
		 * Returns the subject.
		 * @return String
		 */
		
		public String getRname() {
			return this.rname;
		}

		/** 
		 * Set the name.
		 * @param sname The name to set
		 */
		public void setRname(String rname) {
			this.rname = rname;
		}
		/** 
		 * Returns the subject.
		 * @return String
		 */
		
		public String getRemail() {
			return this.semail;
		}

		/** 
		 * Set the semail.
		 * @param semail The semail to set
		 */
		public void setRemail(String remail) {
			this.remail = remail;
		}
		
		/** 
		 * Returns the subject.
		 * @return String
		 */
		
		public String getSname() {
			return this.sname;
		}

		/** 
		 * Set the sname.
		 * @param sname The sname to set
		 */
		public void setSname(String sname) {
			this.sname = sname;
		}
		public String getSemail() {
			return this.remail;
		}

		/** 
		 * Set the semail.
		 * @param semail The semail to set
		 */
		public void setSemail(String semail) {
			this.semail = semail;
		}
		/** 
		 * Returns the subject.
		 * @return String
		 */
		public String getSubject() {
			return this.subject;
		}

		/** 
		 * Set the subject.
		 * @param subject The subject to set
		 */
		public void setSubject(String subject) {
			this.subject = subject;
		}
		/** 
		 * Returns the message.
		 * @return String
		 */
		public String getMessage() {
			return this.message;
		}

		/** 
		 * Set the message.
		 * @param message The message to set
		 */
		public void setMessage(String message) {
			this.message = message;
		}

		/** 
		 * Returns the copy.
		 * @return String
		 */
		public String getCopy() {
			return this.copy;
		}

		/** 
		 * Set the copy.
		 * @param copy The copy copy set
		 */
		public void setCopy(String copy) {
			this.copy = copy;
		}

		
		
		
	}
