/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-11-2007
 * 
 * XDoclet definition:
 * @struts.form name="writeComplaintForm"
 */
public class WriteComplaintForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** text property */
	private String blogTitle;
	private String category;
	private String othercat;
	private String subCategory1;
	private String otherscat1;
	private String subCategory2;
	private String otherbname;
	private String subCategory3;
	private String otherdname;
	private String address;
	private String city;
	private String state;
	private String country;
	private String pincode;
	private String blogtext;
	private String releventtext;
	
	public String getBlogTitle() {
		return blogTitle;
	}

	public void setBlogTitle(String blogTitle) {
		this.blogTitle = blogTitle;
	}
	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getOthercat() {
		return othercat;
	}

	public void setOthercat(String othercat) {
		this.othercat = othercat;
	}

	public String getSubCategory1() {
		return subCategory1;
	}

	public void setSubCategory1(String subCategory1) {
		this.subCategory1 = subCategory1;
	}

	public String getOtherscat1() {
		return otherscat1;
	}

	public void setOtherscat1(String otherscat1) {
		this.otherscat1 = otherscat1;
	}

	public String getSubCategory2() {
		return subCategory2;
	}

	public void setSubCategory2(String subCategory2) {
		this.subCategory2 = subCategory2;
	}

	public String getOtherbname() {
		return otherbname;
	}

	public void setOtherbname(String otherbname) {
		this.otherbname = otherbname;
	}

	public String getSubCategory3() {
		return subCategory3;
	}

	public void setSubCategory3(String subCategory3) {
		this.subCategory3 = subCategory3;
	}

	public String getOtherdname() {
		return otherdname;
	}

	public void setOtherdname(String otherdname) {
		this.otherdname = otherdname;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}
	public String getPincode() {
		return pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	public String getBlogtext() {
		return blogtext;
	}

	public void setBlogtext(String blogtext) {
		this.blogtext = blogtext;
	}

	public String getReleventtext() {
		return releventtext;
	}

	public void setReleventtexty(String releventtext) {
		this.releventtext = releventtext;
	}



	/** 
	 * Returns the title.
	 * @return String
	 */
	
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest req)
	{
		ActionErrors errors = new ActionErrors();
		if(blogTitle==null || blogTitle.length()==0)
			errors.add("blogTitle",new ActionError("errors.blogTitle.required"));
		
		
		return errors;
	}
}