/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.mm.struts.indv.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mm.core.master.IndvMaster;
import com.mm.core.master.RootMaster;
import com.mm.struts.indv.form.ModifyDraftForm;
import com.sun.org.apache.xerces.internal.parsers.IntegratedParserConfiguration;

import java.util.Vector;
/** 
 * MyEclipse Struts
 * Creation date: 07-19-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class DraftModifyAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String status = "failure";
		HttpSession session =request.getSession();
		String userid=(String)session.getAttribute("uId");
		String draftid= request.getParameter("numDraftId");
		IndvMaster indvMaster = new IndvMaster();
		
		DataSource dataSource = getDataSource(request,"indv");
		
		//set parameter vector for gettin gdetail by using indvMaster's get draft information 
		Vector <String> paramVec = new Vector<String>();
		paramVec.add(draftid);
		paramVec.add(userid);
		Vector dataVec = indvMaster.getDraftUnnamedData(dataSource, Integer.parseInt(draftid.trim()));
		
		Vector draftVec = indvMaster.getDraftsDetails(dataSource,paramVec);
		//System.out.println("draftVec in draft modify>>>"+draftVec);
		/*
		 * draftVec contain data in this sequence
		  	draft_id				//0
			draft_title				//1
			draft_text				//2
			relevent_info			//3		
		 	category				//4
			creation_date			//5
			creation_time			//6
			lastmodify_date			//7		
			lastmodify_time			//8
		 	login_id				//9
		 	companyid				//10
			timepart				//11
		 	dealer_id				//12
			other					//13
			advt_id					//14
		 */
		String strCid = "94~+91", strSid="0", strPid="0";
		if(draftVec.size()>0)
		{
			ModifyDraftForm modifyDraftForm = new ModifyDraftForm();
			modifyDraftForm.setBlogTitle(draftVec.elementAt(1).toString().trim());
			modifyDraftForm.setCategory(draftVec.elementAt(4).toString().trim());
			if(draftVec.elementAt(14).toString().trim().equals("0"))
			{
				modifyDraftForm.setOtherBrand(draftVec.elementAt(13).toString().trim());
				modifyDraftForm.setBrand("-1");
			}
			else
			{
				modifyDraftForm.setOtherBrand("");
				modifyDraftForm.setBrand(draftVec.elementAt(14).toString().trim());
			}
			int dealerId = Integer.parseInt(draftVec.elementAt(12).toString().trim());
			
			if(dealerId == 0)
			{
				modifyDraftForm.setCheckDealer("");
				modifyDraftForm.setDealerName("");
				modifyDraftForm.setAddress("");
				modifyDraftForm.setCountry("0~+0");
				modifyDraftForm.setState("0");
				modifyDraftForm.setCity("0");
				modifyDraftForm.setPincode("000000");
				strCid = "94~+91";
				strSid="0";
				strPid="0";
			}
			else
			{
				
				modifyDraftForm.setCheckDealer("checked");
				Vector dealerVec1 = indvMaster.getDealerDetail(dataSource,dealerId);
				System.out.println("dealerVec1 in draft modify>>>"+dealerVec1);				
				modifyDraftForm.setDealerName(dealerVec1.elementAt(1).toString().trim());
				modifyDraftForm.setAddress(dealerVec1.elementAt(4).toString().trim());
				
				System.out.println("dealerVec1.................draftmodify............."+dealerVec1.elementAt(4).toString().trim());
				
				strCid = dealerVec1.elementAt(5).toString().trim();
				strSid=dealerVec1.elementAt(6).toString().trim();
				strPid=dealerVec1.elementAt(8).toString().trim();
				//modifyDraftForm.setCountry(dealerVec1.elementAt(5).toString().trim());
				//modifyDraftForm.setState(dealerVec1.elementAt(6).toString().trim());
				//modifyDraftForm.setCity(dealerVec1.elementAt(8).toString().trim());
				modifyDraftForm.setPincode(dealerVec1.elementAt(12).toString().trim());
			}
					
			modifyDraftForm.setBlogtext(draftVec.elementAt(2).toString().trim());
			modifyDraftForm.setReleventtext(draftVec.elementAt(3).toString().trim());
			modifyDraftForm.setDraftId(draftid);
			modifyDraftForm.setDealerId(String.valueOf(dealerId));
			request.setAttribute("indvModifyDraftForm", modifyDraftForm);
			
			
			status = "success";
		}
		int numEnabled = indvMaster.getStrCategoryName(dataSource, Integer.parseInt(draftVec.elementAt(4).toString().trim()));
		String strCatId="0", strOtherCat="NullNone";
		if(numEnabled==0)
		{
			strCatId="-1";
			RootMaster rm = new RootMaster();
			strOtherCat= rm.getStrCategoryName(dataSource, Integer.parseInt(draftVec.elementAt(4).toString().trim()));
		}
		else
		{
			strCatId=draftVec.elementAt(4).toString().trim();
			strOtherCat="NullNone";
		}
		System.out.println("strCid "+strCid);
		session.setAttribute("cid", strCid);
		session.setAttribute("sid", strSid);
		session.setAttribute("pid", strPid);
		
		session.setAttribute("complaintUnnamedData", dataVec);
		session.setAttribute("catid", strCatId);
		session.setAttribute("otherCatid", strOtherCat);
		session.setAttribute("Bid", draftVec.elementAt(14).toString().trim());
		session.setAttribute("otherBid", (draftVec.elementAt(13).toString().trim().equalsIgnoreCase("")) ? "NullNone" : draftVec.elementAt(13).toString().trim());
		return mapping.findForward(status);
	}
}