
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */

package com.mm.struts.indv.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import javax.servlet.http.HttpSession;

/** 
 * MyEclipse Struts
 * Creation date: 06-20-2007
 * 
 * XDoclet definition:
 * @struts.form name="ChangepassForm"
 */
public class ResponseForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** text property */
	private String responsetext= "";
	
	/** 
	 * Returns the currentPass.
	 * @return String
	 */
	public String getResponsetext() {
		return this.responsetext;
	}
	/** 
	 * Set the currentPass.
	 * @param currentPass The currentPass to set
	 */
	public void setResponsetext(String responsetext) {
		this.responsetext = responsetext;
	}
	
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest req)
	{
		ActionErrors errors = new ActionErrors();
		HttpSession session = req.getSession();
		System.out.println("manoj in form");
		if(this.responsetext.length()<=0)
		{
			//System.out.println("manoj in form if");
			errors.add("indvResponseForm",new ActionError("errors.required","Response"));
			session.setAttribute("result", "failure");
		}
		else if(this.responsetext.length()>1500)
		{
			//System.out.println("manoj in form else if");
			errors.add("indvResponseForm",new ActionError("errors.resource.length","Response","1500"));
			session.setAttribute("result", "failure");
		}
		else
		{
			//System.out.println("manoj in form else");
			session.setAttribute("result", "success");
		}
		return errors;
	}
	
	
}